"""The generalized R DE script, emitted to a temp dir by the runner.

This is a faithful generalization of the user's reference pipeline
(``test_matrix/pipeline_cab_rnaseq_de_finalized_050924_cov_rep_fixed.R``):

    edgeR  DGEList -> CPM filter -> calcNormFactors (TMM)
    design ~ [batch +] [covariates +] Group   (Group releveled to the reference)
    limma  voom -> lmFit -> contrasts.fit -> eBayes  (moderated t-test)
    topTable  ->  <contrast>_DE.txt

The method is therefore **edgeR (TMM + filtering) + limma-voom with empirical
Bayes moderated t-test** — reported as such, never as edgeR alone.

The script is data-driven: it reads a ``run_spec.json`` (paths, group column,
reference/comparison groups, covariates, batch, filtering) so no paths are
hard-coded. It writes DE tables, the voom-normalized matrix, a versions file, a
method descriptor, and a log.
"""

RNASEQ_DE_R = r'''#!/usr/bin/env Rscript
# Generated by Make My Figure — reproducible RNA-seq DE (edgeR + limma-voom).
suppressWarnings(suppressMessages({
  ok <- requireNamespace("jsonlite", quietly = TRUE)
}))
if (!ok) { cat("MMF_ERROR: package 'jsonlite' is required\n"); quit(status = 3) }
args <- commandArgs(trailingOnly = TRUE)
spec_path <- if (length(args) >= 1) args[[1]] else "run_spec.json"
spec <- jsonlite::fromJSON(spec_path)
outdir <- spec$output_dir
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
logfile <- file.path(outdir, "analysis_log.txt")
log_con <- file(logfile, open = "wt")
logmsg <- function(...) { cat(sprintf(...), "\n", file = log_con, append = TRUE); flush(log_con) }

need <- c("edgeR", "limma")
missing <- need[!vapply(need, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing) > 0) {
  cat(sprintf("MMF_ERROR: missing R packages: %s\n", paste(missing, collapse = ", ")))
  quit(status = 4)
}
suppressWarnings(suppressMessages({ library(edgeR); library(limma) }))

logmsg("Reading counts: %s", spec$counts_file)
counts <- read.table(spec$counts_file, sep = "\t", header = TRUE,
                     row.names = 1, check.names = FALSE)
counts <- as.matrix(counts)
mode(counts) <- "numeric"
counts[is.na(counts)] <- 0
counts <- round(counts)

meta <- read.csv(spec$meta_file, check.names = FALSE, stringsAsFactors = FALSE)
sid  <- spec$sample_id_col
grp  <- spec$group_col
meta[[grp]] <- gsub(" ", "_", as.character(meta[[grp]]))

# Align samples (preserve metadata order).
keep_samples <- intersect(as.character(meta[[sid]]), colnames(counts))
meta <- meta[as.character(meta[[sid]]) %in% keep_samples, , drop = FALSE]
counts <- counts[, as.character(meta[[sid]]), drop = FALSE]
logmsg("Samples used: %d ; genes in: %d", ncol(counts), nrow(counts))

# Group factor, releveled so the reference group is the baseline.
ref <- spec$reference_group
lev <- unique(c(ref, meta[[grp]]))
meta$.Group <- factor(meta[[grp]], levels = lev)

# Optional annotation (gene_id -> symbol/biotype/...).
annot <- NULL
if (!is.null(spec$annotation_file) && nzchar(spec$annotation_file)) {
  annot <- read.table(spec$annotation_file, sep = "\t", header = TRUE,
                       row.names = 1, check.names = FALSE, stringsAsFactors = FALSE)
}

# ---- edgeR: DGEList, CPM filter, TMM normalization ----
dge <- DGEList(counts = counts, group = meta$.Group)
min_samples <- min(table(meta$.Group))
cpm_cut <- if (!is.null(spec$min_cpm)) spec$min_cpm else 1
keep <- rowSums(cpm(dge) > cpm_cut) >= min_samples
dge <- dge[keep, , keep.lib.sizes = FALSE]
dge <- calcNormFactors(dge)   # TMM
logmsg("Genes after filter (CPM>%s in >=%d samples): %d", cpm_cut, min_samples, nrow(dge))

# ---- design: [batch +] [covariates +] Group ----
rhs <- c()
if (!is.null(spec$batch) && nzchar(spec$batch)) {
  meta[[spec$batch]] <- factor(meta[[spec$batch]]); rhs <- c(rhs, spec$batch)
}
covs <- spec$covariates
if (!is.null(covs)) for (cv in covs) {
  if (is.character(meta[[cv]])) meta[[cv]] <- factor(meta[[cv]])
  rhs <- c(rhs, cv)
}
rhs <- c(rhs, ".Group")
form <- as.formula(paste("~", paste(rhs, collapse = " + ")))
design <- model.matrix(form, data = meta)
design_formula_report <- gsub("\\.Group", grp, paste(deparse(form), collapse = ""))
logmsg("Design: %s", design_formula_report)

# ---- limma-voom + eBayes ----
v <- voom(dge, design, plot = FALSE)
E <- v$E
voom_out <- file.path(outdir, "voom_norm_annot.txt")
if (!is.null(annot)) {
  common <- intersect(rownames(E), rownames(annot))
  write.table(cbind(annot[rownames(E), , drop = FALSE], E), file = voom_out,
              sep = "\t", quote = FALSE, row.names = TRUE)
} else {
  write.table(E, file = voom_out, sep = "\t", quote = FALSE, row.names = TRUE)
}
fit <- lmFit(v, design)

make_contrast <- function(g1, g2, cols) {
  c1 <- paste0(".Group", g1); c2 <- paste0(".Group", g2)
  h1 <- c1 %in% cols; h2 <- c2 %in% cols
  if (h1 && h2) paste0(c1, " - ", c2)
  else if (h1 && !h2) c1
  else if (!h1 && h2) paste0("-(", c2, ")")
  else stop(sprintf("contrast groups not in design: %s / %s", g1, g2))
}
comps <- spec$comparisons
if (is.data.frame(comps)) {
  comp_list <- lapply(seq_len(nrow(comps)), function(i)
    list(group1 = comps$group1[i], group2 = comps$group2[i]))
} else comp_list <- comps

design_cols <- colnames(design)
contr_strs <- vapply(comp_list, function(c) make_contrast(c$group1, c$group2, design_cols), "")
names(contr_strs) <- vapply(comp_list, function(c) sprintf("%s_vs_%s", c$group1, c$group2), "")
cont_mat <- makeContrasts(contrasts = contr_strs, levels = design)
colnames(cont_mat) <- names(contr_strs)

fit2 <- eBayes(contrasts.fit(fit, cont_mat))
de_files <- c()
for (cn in colnames(cont_mat)) {
  tt <- topTable(fit2, coef = cn, number = Inf, sort.by = "P")
  if (!is.null(annot)) tt <- cbind(annot[rownames(tt), , drop = FALSE], tt)
  f <- file.path(outdir, paste0(cn, "_DE.txt"))
  write.table(tt, file = f, sep = "\t", quote = FALSE, row.names = TRUE)
  de_files <- c(de_files, f)
  logmsg("Wrote DE table: %s (%d genes)", f, nrow(tt))
}

# ---- versions + method descriptor ----
pkg_ver <- function(p) tryCatch(as.character(utils::packageVersion(p)), error = function(e) NA)
versions <- list(r_version = R.version.string,
                 edgeR = pkg_ver("edgeR"), limma = pkg_ver("limma"),
                 statmod = pkg_ver("statmod"))
jsonlite::write_json(versions, file.path(outdir, "versions.json"), auto_unbox = TRUE)

method <- list(
  de_method_id = "edger_limma_voom",
  de_method = "edgeR (TMM normalization + filtering) with limma-voom and empirical Bayes moderated t-test",
  normalization = "edgeR TMM (calcNormFactors) + limma voom",
  design_formula = design_formula_report,
  contrasts = as.list(contr_strs),
  contrast_names = names(contr_strs),
  filtering = sprintf("CPM > %s in >= %d samples", cpm_cut, min_samples),
  de_files = as.list(basename(de_files)),
  voom_file = basename(voom_out),
  statistic = "moderated t (limma eBayes)",
  adjust_method = "BH"
)
jsonlite::write_json(method, file.path(outdir, "method.json"), auto_unbox = TRUE)
logmsg("Pipeline complete.")
cat("MMF_OK\n")
close(log_con)
'''
