"""Plot-aware style capabilities — which Publication controls a plot type honors.

The single visible style is **Publication**. Not every control applies to every
plot: a network diagram has no axes (so axis-label padding is meaningless) and uses
node/edge colors instead of a marker size or bar palette. This registry lets the GUI
show the right controls, disable the rest with an honest reason, and lets the render
path *warn* (never silently ignore) when a style key does not apply.

Usage:
  caps = get_style_capabilities("network_graph")
  applied = filter_style_controls_for_plot("network_graph", spec_style)
  warns = warn_ignored_style_controls("network_graph", spec_style)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class PlotStyleCapabilities:
    plot_type: str
    supports_axes: bool = True
    supports_x_tick_rotation: bool = True
    supports_y_tick_rotation: bool = True
    supports_axis_label_padding: bool = True
    supports_legend: bool = True
    supports_palette: bool = True            # categorical palette (bars/box/points/groups)
    supports_group_colors: bool = True
    # One flag was not enough. A dot plot ramps a single magnitude and reads
    # sequential_cmap only, so a "Diverging map" chooser shown beside it did
    # nothing - visible, and unable to act. The two are declared separately now;
    # supports_continuous_colormap stays as "either kind applies" so anything
    # that already asks the old question is unaffected.
    supports_continuous_colormap: bool = False
    supports_sequential_cmap: bool = False
    supports_diverging_cmap: bool = False
    supports_colorbar: bool = False
    supports_node_colors: bool = False
    supports_edge_colors: bool = False
    supports_label_colors: bool = True
    supports_panel_background: bool = True
    supports_marker_size: bool = True
    supports_line_width: bool = True
    supports_annotation_controls: bool = True
    unsupported_controls_reason: str = "does not apply to this plot type"


# Map each style-spec key to the capability flag that gates it. A key mapped to
# ``None`` is universal (font/size/figure/DPI/background/padding) and always applies.
STYLE_CONTROL_CAPABILITY: Dict[str, str] = {
    "palette_name": "supports_palette",
    "color_overrides": "supports_group_colors",
    "marker_size": "supports_marker_size",
    "line_width_pt": "supports_line_width",
    "legend_pt": "supports_legend",
    "legend_outside": "supports_legend",
    "node_color": "supports_node_colors",
    "node_color_map": "supports_node_colors",
    "edge_color": "supports_edge_colors",
    "edge_color_positive": "supports_edge_colors",
    "edge_color_negative": "supports_edge_colors",
    "label_color": "supports_label_colors",
    "sequential_cmap": "supports_sequential_cmap",
    "diverging_cmap": "supports_diverging_cmap",
    "colorbar_label": "supports_colorbar",
}

# Universal controls — always applicable regardless of plot type.
_UNIVERSAL = {
    "font_family", "axis_font_pt", "tick_label_pt", "title_font_pt", "annotation_pt",
    "dpi", "figure_width_mm", "figure_height_mm", "background", "panel_background",
    "x_label_pad", "y_label_pad", "title_pad", "x_tick_rotation", "y_tick_rotation",
}

_DEFAULT = PlotStyleCapabilities(plot_type="_default")

# Per-plot capabilities. GENERATED by scripts/audit_style_capabilities.py --write from
# what each renderer's source actually reads; hand-written reasons are kept in that
# script's _REASONS table. Do not edit the flags by hand - fix the renderer or the
# script, then regenerate, so a control is never declared to work when it does not.
_CAPS: Dict[str, PlotStyleCapabilities] = {
    "barplot_with_error_bar": PlotStyleCapabilities(
        plot_type="barplot_with_error_bar", supports_line_width=False,
        unsupported_controls_reason=(
            "bars have no markers or data lines; error-bar and edge widths come from the "
            "profile")),
    "grouped_barplot_with_error_bar": PlotStyleCapabilities(
        plot_type="grouped_barplot_with_error_bar", supports_line_width=False,
        unsupported_controls_reason=(
            "bars have no markers or data lines; error-bar and edge widths come from the "
            "profile")),
    "heatmap_clustered_matrix": PlotStyleCapabilities(
        plot_type="heatmap_clustered_matrix", supports_group_colors=False,
        supports_continuous_colormap=True, supports_sequential_cmap=True, supports_diverging_cmap=True, supports_colorbar=True,
        supports_marker_size=False, supports_line_width=False,
        unsupported_controls_reason=(
            "heatmaps use a continuous colormap, not per-point markers")),
    # Plots whose colour is one accent, not a set of categories. They advertised
    # the categorical palette and then reached exactly one of its entries, so the
    # control appeared broken rather than inapplicable - and index 0 is blue in
    # two palettes and black in the other two, which is precisely the reported
    # "only black or blue". Each now exposes a picker per artist it actually
    # draws, in the same style the volcano does below.
    "calibration_plot": PlotStyleCapabilities(
        plot_type="calibration_plot", supports_group_colors=False,
        unsupported_controls_reason=(
            "a calibration plot draws one curve against a reference line, not categories - "
            "set the curve, point and reference colours in the plot options")),
    "volcano_plot": PlotStyleCapabilities(
        plot_type="volcano_plot", supports_palette=False, supports_group_colors=False,
        supports_line_width=False,
        unsupported_controls_reason=(
            "a volcano colours points by significance class (up / down / not significant) - "
            "set those three colours in the plot options; the palette does not apply")),
    "lineplot_timecourse_with_error_band": PlotStyleCapabilities(
        plot_type="lineplot_timecourse_with_error_band", supports_marker_size=False),
    "ridge_or_density_plot": PlotStyleCapabilities(
        plot_type="ridge_or_density_plot", supports_marker_size=False),
    "enrichment_dotplot": PlotStyleCapabilities(
        plot_type="enrichment_dotplot", supports_group_colors=False,
        supports_continuous_colormap=True, supports_sequential_cmap=True, supports_colorbar=True,
        supports_marker_size=False, supports_line_width=False),
    "kaplan_meier_survival_curve": PlotStyleCapabilities(
        plot_type="kaplan_meier_survival_curve", supports_marker_size=False),
    "stacked_bar_composition": PlotStyleCapabilities(
        plot_type="stacked_bar_composition", supports_marker_size=False,
        supports_line_width=False,
        unsupported_controls_reason=(
            "stacked bars have no markers or data lines")),
    "waterfall_plot": PlotStyleCapabilities(
        plot_type="waterfall_plot", supports_marker_size=False, supports_line_width=False),
    "pca_scatter_from_matrix": PlotStyleCapabilities(
        plot_type="pca_scatter_from_matrix", supports_line_width=False),
    "oncoprint_mutation_heatmap": PlotStyleCapabilities(
        plot_type="oncoprint_mutation_heatmap", supports_marker_size=False,
        supports_line_width=False,
        unsupported_controls_reason=(
            "oncoprints use categorical mutation colors, not markers")),
    "lollipop_mutation_plot": PlotStyleCapabilities(
        plot_type="lollipop_mutation_plot", supports_marker_size=False),
    "roc_curve": PlotStyleCapabilities(
        plot_type="roc_curve", supports_marker_size=False),
    "forest_plot": PlotStyleCapabilities(
        plot_type="forest_plot", supports_legend=False, supports_marker_size=False,
        supports_group_colors=False,
        unsupported_controls_reason=(
            "a forest plot draws estimates with confidence intervals against a null line, "
            "not categories - set those colours in the plot options")),
    "raincloud_plot": PlotStyleCapabilities(
        plot_type="raincloud_plot", supports_legend=False),
    "hierarchical_dendrogram": PlotStyleCapabilities(
        plot_type="hierarchical_dendrogram", supports_legend=False,
        supports_marker_size=False, supports_line_width=False,
        supports_group_colors=False,
        unsupported_controls_reason=(
            "a dendrogram has no markers, branch width follows the profile, and it draws "
            "one set of branches rather than categories - set the branch colour in the "
            "plot options")),
    "ma_plot": PlotStyleCapabilities(
        plot_type="ma_plot", supports_line_width=False),
    "qq_plot": PlotStyleCapabilities(
        plot_type="qq_plot", supports_legend=False,
        supports_group_colors=False,
        unsupported_controls_reason=(
            "a Q-Q plot draws points against a reference line, not categories - set the "
            "point and reference colours in the plot options")),
    "bland_altman_plot": PlotStyleCapabilities(
        plot_type="bland_altman_plot", supports_legend=False,
        supports_group_colors=False,
        unsupported_controls_reason=(
            "a Bland-Altman plot draws points, a mean-difference line and limits of "
            "agreement, not categories - set those colours in the plot options")),
    "precision_recall_curve": PlotStyleCapabilities(
        plot_type="precision_recall_curve", supports_marker_size=False),
    "confusion_matrix": PlotStyleCapabilities(
        plot_type="confusion_matrix", supports_group_colors=False,
        supports_continuous_colormap=True, supports_sequential_cmap=True, supports_colorbar=True, supports_legend=False,
        supports_marker_size=False, supports_line_width=False),
    "upset_plot": PlotStyleCapabilities(
        plot_type="upset_plot", supports_legend=False),
    "swimmer_plot": PlotStyleCapabilities(
        plot_type="swimmer_plot", supports_line_width=False),
    "sankey_plot": PlotStyleCapabilities(
        plot_type="sankey_plot", supports_legend=False, supports_marker_size=False,
        supports_line_width=False, supports_axes=False, supports_x_tick_rotation=False,
        supports_y_tick_rotation=False, supports_axis_label_padding=False,
        unsupported_controls_reason=(
            "flows have no axes, markers or lines in the plot sense")),
    "embedding_scatter": PlotStyleCapabilities(
        plot_type="embedding_scatter", supports_continuous_colormap=True, supports_sequential_cmap=True,
        supports_colorbar=True, supports_line_width=False),
    "hierarchical_clustering": PlotStyleCapabilities(
        plot_type="hierarchical_clustering", supports_group_colors=False,
        supports_continuous_colormap=True, supports_sequential_cmap=True, supports_diverging_cmap=True, supports_colorbar=True,
        supports_marker_size=False, supports_line_width=False),
    "network_graph": PlotStyleCapabilities(
        plot_type="network_graph", supports_continuous_colormap=True,
        supports_sequential_cmap=True,
        supports_colorbar=True, supports_marker_size=False, supports_line_width=False,
        supports_axes=False, supports_x_tick_rotation=False,
        supports_y_tick_rotation=False, supports_axis_label_padding=False,
        supports_node_colors=True, supports_edge_colors=True,
        unsupported_controls_reason=(
            "does not apply to network plots (they have no axes; use node/edge colors, node "
            "size and edge width instead)")),
    "chord_diagram": PlotStyleCapabilities(
        plot_type="chord_diagram", supports_marker_size=False, supports_line_width=False,
        supports_axes=False, supports_x_tick_rotation=False,
        supports_y_tick_rotation=False, supports_axis_label_padding=False),
    # --- spatial (v2) --------------------------------------------------------
    # Declared from what each renderer actually reads, checked by
    # scripts/audit_style_capabilities.py. Spatial maps draw marks and polygons,
    # not lines, so line-width controls genuinely do not apply.
    "spatial_categorical_map": PlotStyleCapabilities(
        plot_type="spatial_categorical_map", supports_line_width=False,
        unsupported_controls_reason=(
            "a spatial map draws point marks; line styling does not apply")),
    "spatial_feature_map": PlotStyleCapabilities(
        plot_type="spatial_feature_map",
        # The palette control selects the sequential colormap for continuous
        # plots, so it does have an effect here even though there are no
        # categorical colours to set.
        supports_group_colors=False, supports_continuous_colormap=True, supports_sequential_cmap=True,
        supports_colorbar=True, supports_legend=False, supports_line_width=False,
        unsupported_controls_reason=(
            "this map colours by a continuous value: the palette chooses the colormap, "
            "and there are no per-group colours or line styling to set")),
    "spatial_transcript_map": PlotStyleCapabilities(
        plot_type="spatial_transcript_map", supports_line_width=False,
        unsupported_controls_reason=(
            "a transcript map draws point marks; line styling does not apply")),
    "spatial_roi_map": PlotStyleCapabilities(
        plot_type="spatial_roi_map", supports_marker_size=False,
        supports_line_width=False,
        unsupported_controls_reason=(
            "ROI outlines are sized by spatial.roi_linewidth, and the map draws "
            "polygons rather than markers")),
    "spatial_composition_map": PlotStyleCapabilities(
        plot_type="spatial_composition_map", supports_marker_size=False,
        supports_line_width=False,
        unsupported_controls_reason=(
            "glyph size follows spatial.glyph_radius, which is in data units so the "
            "pies stay aligned to the spots")),
    "neighborhood_enrichment_matrix": PlotStyleCapabilities(
        plot_type="neighborhood_enrichment_matrix",
        # The palette now reaches this plot. It used to fall back to a hard-coded
        # "RdBu_r", so declaring it unsupported was accurate; the colormap follows
        # the style's diverging/sequential choice, which is what the palette sets.
        supports_palette=True, supports_continuous_colormap=True, supports_sequential_cmap=True, supports_diverging_cmap=True,
        supports_group_colors=False, supports_colorbar=True,
        supports_marker_size=False, supports_line_width=False,
        unsupported_controls_reason=(
            "point area carries the frequency, so it is set by the data rather "
            "than by the marker-size control")),
}


def get_style_capabilities(plot_type: str) -> PlotStyleCapabilities:
    """Capabilities for ``plot_type`` (the axes-based default if unlisted)."""
    caps = _CAPS.get(plot_type)
    if caps is not None:
        return caps
    return PlotStyleCapabilities(plot_type=plot_type)


def _supported(caps: PlotStyleCapabilities, key: str) -> bool:
    if key in _UNIVERSAL:
        return True
    flag = STYLE_CONTROL_CAPABILITY.get(key)
    if flag is None:
        return True                      # unknown key: treat as universal (don't hide)
    return bool(getattr(caps, flag, True))


def filter_style_controls_for_plot(plot_type: str, style_spec: Dict) -> Dict:
    """Return only the style keys that ``plot_type`` actually consumes."""
    caps = get_style_capabilities(plot_type)
    return {k: v for k, v in (style_spec or {}).items() if _supported(caps, k)}


def validate_style_controls_for_plot(plot_type: str, style_spec: Dict
                                     ) -> List[Tuple[str, bool, str]]:
    """(key, is_supported, reason) for every key present in ``style_spec``."""
    caps = get_style_capabilities(plot_type)
    out: List[Tuple[str, bool, str]] = []
    for k in (style_spec or {}):
        ok = _supported(caps, k)
        out.append((k, ok, "" if ok else caps.unsupported_controls_reason))
    return out


def warn_ignored_style_controls(plot_type: str, style_spec: Dict) -> List[str]:
    """Human-readable warnings for present-but-unsupported style controls.

    Used by the render path so an inapplicable control is reported, never silently
    ignored."""
    caps = get_style_capabilities(plot_type)
    warns: List[str] = []
    for k, v in (style_spec or {}).items():
        if v is None:
            continue
        if not _supported(caps, k):
            warns.append(f"Style control '{k}' {caps.unsupported_controls_reason}; it was "
                         f"ignored for this {plot_type}.")
    return warns


def applicable_controls(plot_type: str, control_keys: List[str]) -> List[Tuple[str, bool, str]]:
    """For the GUI: for each candidate control key, (key, enabled, disabled_reason).

    Enabled controls should be shown; disabled ones shown greyed with the reason as a
    tooltip (never hidden silently unless the GUI prefers to hide)."""
    caps = get_style_capabilities(plot_type)
    return [(k, _supported(caps, k),
             "" if _supported(caps, k) else caps.unsupported_controls_reason)
            for k in control_keys]
