#!/usr/bin/env python
"""Publication-QC gallery for every plot type (v0.6).

For each plot type registered in ``make_my_figure_core.plots.registry``, this
script loads the bundled example dataset, renders it with the single
Publication style, exports a PNG, scores the render with
``make_my_figure_core.qc.score_publication``, and writes a Markdown summary
table. It is a regression/QA gallery, not a benchmark of any specific journal
figure — see ``docs/PUBLICATION_QC.md`` and ``docs/PUBLICATION_BENCHMARKS.md``.

Make My Figure does not run RNA-seq differential-expression analysis; the
volcano example here plots a bundled precomputed differential-results table
(fold-change + p-value columns), exactly like a user-supplied one would be.

Outputs (git-ignored, regenerate on demand):
    outputs/publication_qc/v0_6/<plot_type>.png
    outputs/publication_qc/v0_6/README.md

Usage:
    python scripts/generate_v0_6_qc_gallery.py
    python scripts/generate_v0_6_qc_gallery.py --out outputs/publication_qc/v0_6

Deterministic: uses the committed example datasets and the Agg backend only;
no network access, no randomness.
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any, Dict, List, Optional

import matplotlib

matplotlib.use("Agg")

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

DEFAULT_OUT = os.path.join(_ROOT, "outputs", "publication_qc", "v0_6")


def _render_one(plot_type: str, out_dir: str) -> Dict[str, Any]:
    """Load, render, export, and QC-score a single plot type's example."""
    import matplotlib.pyplot as plt

    from make_my_figure_core.examples import load_example
    from make_my_figure_core.plots.registry import (
        default_mapping,
        export_figure,
        make_spec,
        render,
    )
    from make_my_figure_core.qc import score_publication

    table_info, aux, plotspec = load_example(plot_type)
    aux_dfs = {name: info.dataframe for name, info in aux.items()}

    spec = dict(plotspec) if plotspec else make_spec(
        plot_type, table_info.source_name, "publication",
        mapping=default_mapping(plot_type))
    # Always score/render the single Publication style, regardless of what an
    # older bundled PlotSpec happened to record.
    spec["journal_style"] = "publication"

    record: Dict[str, Any] = {
        "plot_type": plot_type,
        "dataset": table_info.source_name,
    }
    fig = None
    try:
        result = render(spec, table_info.dataframe, aux=aux_dfs)
        fig = result.figure
        score = score_publication(result=result, spec=spec)
        png_path = os.path.join(out_dir, f"{plot_type}.png")
        export_figure(fig, os.path.join(out_dir, plot_type), ["png"], dpi=300)
        record.update({
            "status": "rendered",
            "png": os.path.relpath(png_path, out_dir),
            "qc_level": score.level,
            "qc_score": score.score,
            "warnings": [c.message for c in score.issues()],
        })
    except Exception as exc:  # noqa: BLE001 - one failure must not abort the gallery
        record.update({
            "status": "error",
            "png": None,
            "qc_level": "error",
            "qc_score": None,
            "warnings": [f"{type(exc).__name__}: {exc}"],
        })
    finally:
        if fig is not None:
            plt.close(fig)
    return record


def run_gallery(out_dir: str) -> List[Dict[str, Any]]:
    from make_my_figure_core.plots.registry import available_plot_types, display_name

    os.makedirs(out_dir, exist_ok=True)
    records: List[Dict[str, Any]] = []
    for plot_type in available_plot_types():
        rec = _render_one(plot_type, out_dir)
        rec["display_name"] = display_name(plot_type)
        records.append(rec)
    return records


def render_readme(records: List[Dict[str, Any]]) -> str:
    n = len(records)
    passed = sum(1 for r in records if r["qc_level"] == "pass")
    warned = sum(1 for r in records if r["qc_level"] == "warn")
    failed = sum(1 for r in records if r["qc_level"] == "fail")
    errored = sum(1 for r in records if r["qc_level"] == "error")

    lines: List[str] = []
    lines.append("# Publication QC gallery (v0.6)\n")
    lines.append(
        "Generated by `scripts/generate_v0_6_qc_gallery.py`. Every plot type is "
        "rendered from its bundled example dataset with the single **Publication** "
        "style and scored with `make_my_figure_core.qc.score_publication`. This is "
        "a regression/QA gallery for the app's own renderers — it does not claim "
        "compliance with any journal's formatting requirements, and the volcano "
        "example plots a bundled **precomputed** differential-results table "
        "(Make My Figure does not run RNA-seq differential-expression analysis).\n")
    lines.append(f"**Summary: {n} plot types — {passed} pass, {warned} warn, "
                 f"{failed} fail, {errored} error.**\n")
    lines.append("| Plot type | Dataset | QC level | Score | Warnings |")
    lines.append("|---|---|---|---|---|")
    for r in records:
        warn_text = "; ".join(r["warnings"]) if r["warnings"] else "—"
        score_text = "n/a" if r["qc_score"] is None else str(r["qc_score"])
        lines.append(f"| {r['display_name']} (`{r['plot_type']}`) | `{r['dataset']}` | "
                     f"{r['qc_level']} | {score_text} | {warn_text} |")
    lines.append("")
    lines.append("See `docs/PUBLICATION_QC.md` for what each check means and "
                 "`docs/RECOMMENDED_FIGURES.md` / `docs/PUBLICATION_BENCHMARKS.md` "
                 "for related tooling.")
    return "\n".join(lines)


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description="Make My Figure v0.6 publication-QC gallery")
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help="output directory for PNGs + README.md (default: %(default)s)")
    args = ap.parse_args(argv)

    out_dir = os.path.abspath(args.out)
    records = run_gallery(out_dir)
    readme = render_readme(records)
    readme_path = os.path.join(out_dir, "README.md")
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(readme)

    passed = sum(1 for r in records if r["qc_level"] == "pass")
    warned = sum(1 for r in records if r["qc_level"] == "warn")
    failed = sum(1 for r in records if r["qc_level"] == "fail")
    errored = sum(1 for r in records if r["qc_level"] == "error")
    print(f"Rendered {len(records)} plot types -> {out_dir}")
    print(f"QC: {passed} pass, {warned} warn, {failed} fail, {errored} error")
    print(f"Wrote {readme_path}")
    return 1 if (failed or errored) else 0


if __name__ == "__main__":
    raise SystemExit(main())
