"""Generate the bundled example datasets for the spatial plot types.

Four of the six are built from **real published data**: one CODEX tissue image
from the colorectal-cancer dataset of Schürch et al. (Cell 2020), deposited on
Mendeley Data under CC BY 4.0 and therefore redistributable with attribution.
Using a real section matters here - the columns, the coordinate ranges, the cell
type names and the class imbalance are all things a user will meet in their own
export, and a simulation quietly smooths every one of them.

Two examples stay synthetic because the CRC dataset has no counterpart:

* the transcript map - CODEX is a protein imaging assay and has no transcript
  coordinates, so a "real" transcript example would have to be faked anyway;
* the ROI map - the deposited table carries no polygon geometry.

Each is labelled for what it is in the manifest, so nothing claims to be
published data that is not.

    python scripts/generate_spatial_example_data.py --crc PATH_TO_CRC_CSV
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os

import numpy as np
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BY_TYPE = os.path.join(ROOT, "examples", "by_plot_type")
MANIFEST = os.path.join(ROOT, "examples", "example_data_manifest.json")
DEFAULT_CRC = os.path.join(ROOT, "benchmarks", "spatial_validation", "cntools_2024",
                           "raw", "CRC_clusters_neighborhoods_markers.csv")
CNTOOLS_DERIVED = os.path.join(ROOT, "benchmarks", "spatial_validation", "cntools_2024",
                               "derived", "neighborhood_enrichment_cntools.csv")
SEED = 42
IMAGE = "reg052_B"          # one representative section: 2,192 cells, 16 cell types

CRC_CITATION = ("Schürch CM, et al. Coordinated cellular neighborhood orchestrates "
                "antitumoral immunity at the colorectal cancer invasive front. "
                "Cell 2020. doi:10.1016/j.cell.2020.07.005. Dataset: "
                "doi:10.17632/mpjzbtfgfr.1 (Mendeley Data, CC BY 4.0).")
CNTOOLS_CITATION = ("Tao Y, et al. CNTools: a computational toolbox for cellular "
                    "neighborhood analysis from multiplexed images. PLOS Comput Biol "
                    "2024;20(8):e1012344. doi:10.1371/journal.pcbi.1012344 "
                    "(S1 Data, CC BY 4.0).")

MARKERS = {"CD8": "CD8 - cytotoxic T cells:Cyc_3_ch_2",
           "CD68": "CD68 - macrophages:Cyc_18_ch_4",
           "Ki67": "Ki67 - proliferation:Cyc_5_ch_4",
           "CD4": "CD4 - T helper cells:Cyc_6_ch_3"}


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _write(slug, df, entry, readme=""):
    d = os.path.join(BY_TYPE, slug)
    os.makedirs(d, exist_ok=True)
    df.to_csv(os.path.join(d, "data.csv"), index=False)
    df.to_csv(os.path.join(d, "data.tsv"), sep="\t", index=False)
    with pd.ExcelWriter(os.path.join(d, "data.xlsx")) as xw:
        df.to_excel(xw, sheet_name="data", index=False)
    with open(os.path.join(d, "plotspec.json"), "w", encoding="utf-8") as fh:
        json.dump(entry.pop("_plotspec"), fh, indent=2)
    with open(os.path.join(d, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(readme)
    return entry


def _files(slug):
    f = {k: f"examples/by_plot_type/{slug}/data.{k}" for k in ("csv", "tsv", "xlsx")}
    f["plotspec"] = f"examples/by_plot_type/{slug}/plotspec.json"
    f["readme"] = f"examples/by_plot_type/{slug}/README.md"
    return f


def _spec(plot_type, mapping, spatial, title):
    return {"plot_type": plot_type, "input_table": "data.csv", "mapping": mapping,
            "journal_style": "publication", "layout": {"title": title},
            "spatial": spatial,
            "output": {"formats": ["png", "pdf", "svg"], "dpi": 300,
                       "width_mm": 180, "height_mm": 150}}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--crc", default=DEFAULT_CRC)
    a = ap.parse_args()
    rng = np.random.default_rng(SEED)
    entries = []

    published = dict(
        data_type="published", license="CC BY 4.0",
        recommended_style_profiles=["publication"],
        expected_export_formats=["svg", "png", "pdf", "plot_spec.json"])
    synthetic = dict(
        data_type="synthetic", license="CC0-1.0",
        recommended_style_profiles=["publication"],
        expected_export_formats=["svg", "png", "pdf", "plot_spec.json"],
        source="generated by scripts/generate_spatial_example_data.py",
        provenance="Synthetic; not derived from any published dataset.")

    if not os.path.exists(a.crc):
        print(f"CRC source not found: {a.crc}\n"
              f"Run benchmarks/spatial_validation/cntools_2024/scripts/download.sh first.")
        return 2
    crc_sha = _sha256(a.crc)
    prov = (f"Derived from image {IMAGE} of the CRC CODEX dataset "
            f"(source SHA-256 {crc_sha[:16]}...). {CRC_CITATION} "
            "Changes made: one image selected; columns subset and renamed; "
            "no measured value altered.")

    cols = ["File Name", "ClusterName", "neighborhood10", "X:X", "Y:Y",
            "patients", "groups"] + list(MARKERS.values())
    raw = pd.read_csv(a.crc, usecols=cols, low_memory=False)
    img = raw[raw["File Name"] == IMAGE].copy()
    if img.empty:
        print(f"image {IMAGE} not present in {a.crc}")
        return 2

    cells = pd.DataFrame({
        "cell_id": [f"{IMAGE}_{i:05d}" for i in range(len(img))],
        "x": img["X:X"].to_numpy(), "y": img["Y:Y"].to_numpy(),
        "cell_type": img["ClusterName"].to_numpy(),
        "neighborhood": [f"CN{int(v) + 1}" for v in img["neighborhood10"]],
        "image": IMAGE, "patient": img["patients"].to_numpy(),
    })
    for short, col in MARKERS.items():
        cells[short] = np.round(img[col].to_numpy(dtype=float), 2)

    # ---------------- 1. categorical map (real) ----------------------------
    slug = "spatial_categorical"
    e = dict(plot_type="spatial_categorical_map", name="Spatial map (categories)", slug=slug,
             description=("Cells of a real CODEX tissue section positioned in image "
                          "coordinates and coloured by annotated cell type."),
             use_case="Show where each cell type sits in a tissue section.",
             required_columns=["x", "y", "cell_type"],
             optional_columns=["cell_id", "neighborhood", "image", "patient",
                               "CD8", "CD68", "Ki67", "CD4"],
             files=_files(slug), aux_tables={}, excel_sheet="Spatial_categorical",
             compatible_renderers=["spatial_categorical_map"], n_rows=int(len(cells)),
             source=CRC_CITATION, provenance=prov,
             user_replacement_note=("One row per cell. Replace x/y with your coordinates and "
                                    "cell_type with your labels. These coordinates are image "
                                    "pixels, which is why the example declares "
                                    "coordinate_units='pixel' and draws no physical scale bar."),
             common_mistakes=["Do not mix sections in one table without an image/sample column "
                              "— neighbours are never computed across images.",
                              "Imaging coordinates run y-downward; set orientation='y_down' "
                              "rather than flipping y by hand."],
             **published)
    e["_plotspec"] = _spec("spatial_categorical_map",
                           {"x": "x", "y": "y", "category": "cell_type"},
                           {"coordinate_units": "pixel", "orientation": "y_down",
                            "marker_size": 7, "alpha": 0.9, "legend_columns": 1},
                           f"Annotated cell types, CRC section {IMAGE}")
    entries.append(_write(slug, cells, e, readme=(
        f"# Spatial map (categories)\n\n**Real published data.** One CODEX image ({IMAGE}, "
        f"{len(cells):,} cells, {cells['cell_type'].nunique()} annotated cell types) from the "
        "colorectal-cancer dataset of Schürch et al., *Cell* 2020.\n\n"
        f"{CRC_CITATION}\n\nRedistributed under CC BY 4.0. Changes made: one image selected, "
        "columns subset and renamed; no measured value was altered.\n\n"
        "Coordinates are **image pixels**, so the example declares `coordinate_units='pixel'` "
        "and `orientation='y_down'` — imaging y runs downward, and the renderer flips only "
        "when told to. No physical scale bar is drawn, because pixels carry no stated "
        "physical length.\n\n"
        "`neighborhood` holds the published cellular-neighbourhood assignment, so the same "
        "table also renders as a neighbourhood map by pointing `category` at it.\n")))

    # ---------------- 2. feature map (real) --------------------------------
    slug = "spatial_feature"
    e = dict(plot_type="spatial_feature_map", name="Spatial map (continuous value)", slug=slug,
             description="Cells coloured by a measured marker intensity from a real CODEX image.",
             use_case="Show where a protein marker is expressed across a section.",
             required_columns=["x", "y", "CD8"],
             optional_columns=["cell_id", "cell_type", "neighborhood", "CD68", "Ki67", "CD4"],
             files=_files(slug), aux_tables={}, excel_sheet="Spatial_feature",
             compatible_renderers=["spatial_feature_map"], n_rows=int(len(cells)),
             source=CRC_CITATION, provenance=prov,
             user_replacement_note=("Replace CD8 with your own measurement column. These are "
                                    "raw CODEX intensities, deliberately untransformed: set "
                                    "spatial.transform yourself and the colourbar label follows."),
             common_mistakes=["Do not pre-log the values and leave the label saying the raw "
                              "marker name — set spatial.transform so the colourbar is honest.",
                              "These intensities contain exact zeros, so log2/log10 are refused; "
                              "use log1p or log2p1."],
             **published)
    e["_plotspec"] = _spec("spatial_feature_map", {"x": "x", "y": "y", "value": "CD8"},
                           {"coordinate_units": "pixel", "orientation": "y_down",
                            "marker_size": 8, "transform": "log1p",
                            "colorbar_label": "log(1 + CD8 intensity)"},
                           f"CD8 intensity, CRC section {IMAGE}")
    entries.append(_write(slug, cells, e, readme=(
        f"# Spatial map (continuous value)\n\n**Real published data** — same CODEX image as the "
        "categorical example, coloured by measured marker intensity (CD8, CD68, Ki67, CD4 "
        "columns available).\n\n"
        f"{CRC_CITATION}\n\nRedistributed under CC BY 4.0.\n\n"
        "The bundled spec uses `transform='log1p'` because raw CODEX intensities are strongly "
        "right-skewed **and contain exact zeros** — `log2`/`log10` are refused outright rather "
        "than nudged. The colourbar is labelled `log(1 + CD8 intensity)` so the transform is "
        "visible in the figure, not buried in a spec file.\n")))

    # ---------------- 3. transcript map (synthetic, and says so) -----------
    genes = ["EPCAM", "CD8A", "COL1A1", "MS4A1", "PECAM1"]
    cx, cy = float(cells["x"].mean()), float(cells["y"].mean())
    rows = []
    for gi, g in enumerate(genes):
        n = [2200, 1100, 1500, 600, 700][gi]
        if g == "EPCAM":
            ang = rng.uniform(0, 2 * np.pi, n); rad = np.sqrt(rng.uniform(0, 1, n)) * 380
        elif g in ("CD8A", "MS4A1"):
            ang = rng.uniform(0, 2 * np.pi, n)
            rad = (520 if g == "CD8A" else 620) + rng.normal(0, 60, n)
        else:
            ang = rng.uniform(0, 2 * np.pi, n); rad = np.sqrt(rng.uniform(0, 1, n)) * 700
        rows.append(pd.DataFrame({
            "transcript_id": [f"t_{g}_{i:06d}" for i in range(n)],
            "x": np.round(cx + rad * np.cos(ang), 2),
            "y": np.round(cy + rad * np.sin(ang), 2),
            "gene": g, "qv": np.round(rng.uniform(20, 40, n), 2)}))
    tx = pd.concat(rows, ignore_index=True).sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    slug = "spatial_transcript"
    e = dict(plot_type="spatial_transcript_map", name="Spatial transcript map", slug=slug,
             description="Individual transcript detections coloured by gene.",
             use_case="Show where transcripts of selected genes were detected in a section.",
             required_columns=["x", "y", "gene"], optional_columns=["transcript_id", "qv"],
             files=_files(slug), aux_tables={}, excel_sheet="Spatial_transcript",
             compatible_renderers=["spatial_transcript_map"], n_rows=int(len(tx)),
             user_replacement_note=("One row per detected transcript. spatial.genes selects "
                                    "which to draw and spatial.min_quality filters on a score "
                                    "column; both are recorded in the figure metadata."),
             common_mistakes=["A transcript table is not a cell table — one row is one "
                              "detection, not one cell.",
                              "Nothing is subsampled automatically; set spatial.max_points for "
                              "an explicit, recorded subsample."],
             **synthetic)
    e["_plotspec"] = _spec("spatial_transcript_map",
                           {"x": "x", "y": "y", "gene": "gene", "quality": "qv"},
                           {"coordinate_units": "pixel", "orientation": "y_down",
                            "marker_size": 1.4, "alpha": 0.55},
                           "Transcripts by gene (synthetic)")
    entries.append(_write(slug, tx, e, readme=(
        "# Spatial transcript map\n\n**Synthetic (CC0), and deliberately so.** The CRC dataset "
        "used by the other spatial examples is CODEX — a protein imaging assay with no "
        "transcript coordinates — so a 'real' transcript example would have to be fabricated "
        "anyway. This one is honestly labelled instead.\n\n"
        f"{len(tx):,} detections across {len(genes)} genes, with a `qv` quality score, laid out "
        "over the same coordinate range as the real section so the scale feels right.\n\n"
        "Dense marks are rasterised inside PDF/SVG while text and axes stay vector. "
        "Subsampling never happens on its own.\n")))

    # ---------------- 4. ROI map (synthetic, derived geometry) -------------
    roi_rows = []
    for name, cat, (ox, oy, rr) in [
            ("ROI_1", "Tumour region", (cx - 250, cy - 120, 330)),
            ("ROI_2", "Immune-rich region", (cx + 330, cy + 180, 260)),
            ("ROI_3", "Stromal region", (cx - 120, cy + 420, 220))]:
        k = 24
        ang = np.linspace(0, 2 * np.pi, k, endpoint=False)
        r = rr * (1 + 0.10 * np.sin(3 * ang) + rng.normal(0, 0.015, k))
        for i in range(k):
            roi_rows.append({"roi_id": name, "vertex_order": i,
                             "x": round(float(ox + r[i] * np.cos(ang[i])), 2),
                             "y": round(float(oy + r[i] * np.sin(ang[i])), 2),
                             "roi_label": name, "roi_category": cat})
    roi = pd.DataFrame(roi_rows)
    slug = "spatial_roi"
    e = dict(plot_type="spatial_roi_map", name="Spatial ROI / region outlines", slug=slug,
             description="Regions of interest drawn as labelled polygon outlines.",
             use_case="Outline and label anatomical or analytical regions on a section.",
             required_columns=["roi_id", "x", "y"],
             optional_columns=["vertex_order", "roi_label", "roi_category"],
             files=_files(slug), aux_tables={}, excel_sheet="Spatial_roi",
             compatible_renderers=["spatial_roi_map"], n_rows=int(len(roi)),
             user_replacement_note=("One row per polygon vertex. Keep vertex_order so the "
                                    "outline is traced in sequence; a repeated closing vertex "
                                    "is fine."),
             common_mistakes=["Unordered vertices produce a self-crossing outline — keep "
                              "vertex_order.",
                              "An ROI with fewer than three vertices is reported and skipped, "
                              "not silently dropped."],
             **synthetic)
    e["_plotspec"] = _spec("spatial_roi_map",
                           {"roi": "roi_id", "x": "x", "y": "y", "vertex_order": "vertex_order",
                            "roi_label": "roi_label", "roi_category": "roi_category"},
                           {"coordinate_units": "pixel", "orientation": "y_down",
                            "roi_fill_alpha": 0.12, "roi_linewidth": 1.6},
                           "Regions of interest (synthetic geometry)")
    entries.append(_write(slug, roi, e, readme=(
        "# Spatial ROI / region outlines\n\n**Synthetic (CC0).** The deposited CRC table carries "
        "no polygon geometry, so these outlines are drawn over the same coordinate range as the "
        "real section rather than taken from it. The region names are descriptive, not "
        "annotations from the source study.\n\n"
        "One row per vertex, ordered by `vertex_order`. Importing geometry someone else defined "
        "is the supported path; there is no freehand drawing tool, because a reproducible ROI "
        "is one that came from a recorded definition.\n")))

    # ---------------- 5. composition glyphs (real, aggregated) -------------
    gx = np.linspace(cells["x"].min(), cells["x"].max(), 9)
    gy = np.linspace(cells["y"].min(), cells["y"].max(), 7)
    step_x = float(gx[1] - gx[0]); step_y = float(gy[1] - gy[0])
    top = list(cells["cell_type"].value_counts().head(7).index)
    comp = []
    for i, sx in enumerate(gx):
        for j, sy in enumerate(gy):
            m = ((cells["x"] - sx).abs() <= step_x / 2) & ((cells["y"] - sy).abs() <= step_y / 2)
            grp = cells[m]
            if len(grp) < 12:
                continue
            counts = grp["cell_type"].value_counts()
            binned = {t: int(counts.get(t, 0)) for t in top}
            binned["other"] = int(len(grp) - sum(binned.values()))
            for ct, c in binned.items():
                if c:
                    comp.append({"spot_id": f"bin_{i:02d}_{j:02d}",
                                 "x": round(float(sx), 1), "y": round(float(sy), 1),
                                 "cell_type": ct, "cell_count": c})
    comp_df = pd.DataFrame(comp)
    slug = "spatial_composition"
    e = dict(plot_type="spatial_composition_map", name="Spatial composition glyphs", slug=slug,
             description=("Cell-type composition of real tissue, aggregated into square bins "
                          "and drawn as pie glyphs."),
             use_case="Show cell-type mixtures across a section, Visium-spot style.",
             required_columns=["spot_id", "x", "y", "cell_type", "cell_count"],
             optional_columns=[], files=_files(slug), aux_tables={},
             excel_sheet="Spatial_composition",
             compatible_renderers=["spatial_composition_map"], n_rows=int(len(comp_df)),
             source=CRC_CITATION,
             provenance=(prov + " Cells were aggregated into a 9x7 grid of square bins; "
                         "bins with fewer than 12 cells were dropped and cell types outside "
                         "the seven most common were pooled as 'other'."),
             user_replacement_note=("Long form: one row per spot and category. These are raw "
                                    "counts, so the spec sets normalize='fraction' to convert "
                                    "them."),
             common_mistakes=["Fractions that do not sum to 1 are reported, not rescaled — a "
                              "short sum usually means a missing category.",
                              "Use top_k or min_fraction to merge rare categories rather than "
                              "drawing unreadable slivers."],
             **published)
    e["_plotspec"] = _spec("spatial_composition_map",
                           {"spot": "spot_id", "x": "x", "y": "y",
                            "category": "cell_type", "value": "cell_count"},
                           {"coordinate_units": "pixel", "orientation": "y_down",
                            "normalize": "fraction"},
                           f"Cell-type composition by bin, CRC section {IMAGE}")
    entries.append(_write(slug, comp_df, e, readme=(
        "# Spatial composition glyphs\n\n**Real published data, aggregated.** The same CODEX "
        f"image ({IMAGE}) binned into a 9x7 grid; each bin is drawn as a pie of its cell-type "
        "mixture.\n\n"
        f"{CRC_CITATION}\n\nRedistributed under CC BY 4.0. Changes made: cells aggregated into "
        "square bins, bins with fewer than 12 cells dropped, and cell types outside the seven "
        "most common pooled as `other`. Counts are exact — nothing was rescaled.\n\n"
        "The spec sets `normalize='fraction'` because the table holds raw counts. With "
        "`normalize='as_given'` the values are drawn exactly as supplied and a short sum is "
        "reported rather than silently rescaled.\n")))

    # ---------------- 6. enrichment matrix (real published values) --------
    slug = "neighborhood_enrichment"
    if os.path.exists(CNTOOLS_DERIVED):
        enr = pd.read_csv(CNTOOLS_DERIVED)
        enr["cell_type"] = ["CT_%02d" % c for c in enr["cell_type_index"]]
        enr = enr[["neighborhood", "cell_type", "enrichment_score",
                   "cell_type_frequency_in_neighborhood"]]
        e = dict(plot_type="neighborhood_enrichment_matrix",
                 name="Cellular-neighbourhood enrichment matrix", slug=slug,
                 description=("Published cell-type enrichment across cellular neighbourhoods; "
                              "colour is the enrichment score, point area the frequency "
                              "within the neighbourhood."),
                 use_case="Show which cell types are enriched in which neighbourhoods.",
                 required_columns=["neighborhood", "cell_type", "enrichment_score"],
                 optional_columns=["cell_type_frequency_in_neighborhood"],
                 files=_files(slug), aux_tables={}, excel_sheet="Neighborhood_enrichment",
                 compatible_renderers=["neighborhood_enrichment_matrix"], n_rows=int(len(enr)),
                 source=CNTOOLS_CITATION,
                 provenance=("Published Fig 3A (CRC, CC*) values from CNTools S1 Data, tidied "
                             "by benchmarks/spatial_validation/cntools_2024. Reproduced from "
                             "the deposited CRC data to 7.8e-14 maximum absolute difference. "
                             "doi:10.1371/journal.pcbi.1012344"),
                 user_replacement_note=("Produced by make_my_figure_core.spatial."
                                        "ct_cn_enrichment from your own cells; the renderer "
                                        "plots these values and never recomputes them."),
                 common_mistakes=["Enrichment is a log ratio: zero means 'as expected', so the "
                                  "colour scale is centred on zero by default.",
                                  "A dot matrix is unreadable without a size key — keep "
                                  "size_legend on."],
                 **published)
        e["_plotspec"] = _spec("neighborhood_enrichment_matrix",
                               {"neighborhood": "neighborhood", "cell_type": "cell_type",
                                "enrichment": "enrichment_score",
                                "frequency": "cell_type_frequency_in_neighborhood"},
                               {"cmap": "RdBu_r", "center": 0.0, "vmin": -6.0, "vmax": 6.0,
                                "colorbar_label": "Enrichment score"},
                               "Cell-type enrichment across neighbourhoods (CNTools Fig 3A)")
        entries.append(_write(slug, enr, e, readme=(
            "# Cellular-neighbourhood enrichment matrix\n\n**Real published data.** The Fig 3A "
            "(CRC, CC*) values from CNTools — 9 neighbourhoods x 28 cell types.\n\n"
            f"{CNTOOLS_CITATION}\n\nRedistributed under CC BY 4.0.\n\n"
            "Colour is the enrichment score, point area the cell type's frequency within that "
            "neighbourhood. Cell types appear as `CT_00`..`CT_27` because the published "
            "spreadsheet does not label its columns.\n\n"
            "`benchmarks/spatial_validation/cntools_2024` reproduces these values from the "
            "deposited CRC data to a maximum absolute difference of 7.8e-14.\n\n"
            "The spec pins `vmin`/`vmax` to +/-6: zero-count cells sit at a pseudocount floor "
            "near -15, and letting them set the range washes every real signal to white. "
            "Values outside the range are drawn at the end colours and the colourbar says so.\n")))
    else:
        print(f"warning: {CNTOOLS_DERIVED} not found; skipping the enrichment example")

    with open(MANIFEST, encoding="utf-8") as fh:
        manifest = json.load(fh)
    new_types = {x["plot_type"] for x in entries}
    manifest["plot_types"] = [e for e in manifest["plot_types"]
                              if e["plot_type"] not in new_types] + entries
    manifest["note"] = (
        "Example datasets are synthetic unless the entry says data_type='published'. Published "
        "entries carry real data under a redistributable licence, with the source, DOI and the "
        "changes made recorded in the entry and its README. Do not cite the synthetic examples "
        "as real findings.")
    with open(MANIFEST, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")

    real = sum(1 for x in entries if x["data_type"] == "published")
    print(f"wrote {len(entries)} spatial examples ({real} from real published data, "
          f"{len(entries) - real} synthetic); manifest has {len(manifest['plot_types'])} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
