"""Reproducible generator for Make My Figure example/template datasets.

Creates, for every plot type the app supports, a clean *synthetic* dataset plus
a CSV/TSV/XLSX copy, a PlotSpec JSON, and a README — under
``examples/by_plot_type/<slug>/`` — a combined workbook, and a machine-readable
manifest.

IMPORTANT: All bundled example data are SYNTHETIC (generated here with a fixed
seed). They look scientifically plausible but are NOT real measurements and must
not be cited as biological findings. Published papers/figures are used by this
project only as visual style references (layout, typography, panels, legends) —
never as a source of copied data.

Safe to re-run: it only writes inside ``examples/``.

Usage:
    python scripts/generate_example_data.py
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from make_my_figure_core.plots.registry import default_mapping, display_name  # noqa: E402

SEED = 42
EXAMPLES_DIR = os.path.join(_ROOT, "examples")
BY_PLOT_DIR = os.path.join(EXAMPLES_DIR, "by_plot_type")
COMBINED_XLSX = os.path.join(EXAMPLES_DIR, "Make_My_Figure_All_Example_Data.xlsx")
MANIFEST_PATH = os.path.join(EXAMPLES_DIR, "example_data_manifest.json")

LICENSE = "CC0-1.0"
SOURCE = "generated by scripts/generate_example_data.py"
STYLES = ["nature_like", "science_like", "cell_like"]


# ---------------------------------------------------------------------------
# Builders — each returns (primary_df, aux_df_or_None). Synthetic biology is
# described in the comments and in each example's README.
# ---------------------------------------------------------------------------
def b_bar_error(rng):
    # qPCR-like relative signal across 4 treatment conditions, 6 replicates each.
    conditions = ["Control", "Drug_A", "Drug_B", "Combination"]
    means = {"Control": 1.0, "Drug_A": 1.6, "Drug_B": 0.7, "Combination": 2.1}
    rows = []
    for cond in conditions:
        for i in range(1, 7):
            rows.append({
                "condition": cond,
                "replicate": f"R{i}",
                "measurement": round(float(rng.normal(means[cond], 0.12)), 3),
                "unit": "relative_signal",
                "experiment_batch": f"Batch_{1 + (i - 1) % 2}",
            })
    return pd.DataFrame(rows), None


def b_grouped_bar(rng):
    # Gene expression by genotype x treatment (two-factor), 5 replicates.
    base = {("WT", "Vehicle"): 1.0, ("WT", "Stimulus"): 1.8,
            ("KO", "Vehicle"): 0.8, ("KO", "Stimulus"): 1.2}
    rows = []
    for geno in ["WT", "KO"]:
        for treat in ["Vehicle", "Stimulus"]:
            for i in range(1, 6):
                rows.append({
                    "genotype": geno, "treatment": treat, "replicate": f"R{i}",
                    "expression": round(float(rng.normal(base[(geno, treat)], 0.1)), 3),
                    "gene": "IL6", "unit": "relative_mRNA",
                })
    return pd.DataFrame(rows), None


def b_box_violin(rng):
    # Biomarker level across three clinical groups, ~24 samples each.
    groups = {"Healthy": 4.5, "Disease": 6.2, "Treated": 5.2}
    rows = []
    n = 0
    for grp, mu in groups.items():
        for _ in range(24):
            n += 1
            rows.append({
                "sample_id": f"S{n:03d}", "group": grp,
                "value": round(float(rng.normal(mu, 0.6)), 3),
                "batch": f"Batch_{rng.integers(1, 4)}",
                "sex": rng.choice(["M", "F"]),
            })
    return pd.DataFrame(rows), None


def b_scatter(rng):
    # Two response groups with different marker-vs-response slopes.
    rows = []
    n = 0
    for grp, slope, intercept, count in [("Responder", 1.4, 1.0, 35),
                                         ("Non_responder", 0.5, 3.0, 25)]:
        for _ in range(count):
            n += 1
            x = float(rng.uniform(1, 9))
            y = slope * x + intercept + float(rng.normal(0, 1.0))
            rows.append({"sample_id": f"S{n:03d}", "x_marker": round(x, 3),
                         "y_response": round(y, 3), "group": grp,
                         "label": f"S{n:03d}" if rng.random() < 0.08 else ""})
    return pd.DataFrame(rows), None


def b_line_timecourse(rng):
    # Signal over time for three treatments, 4 replicates each.
    times = [0, 2, 4, 8, 12, 24, 48]
    rows = []
    for treat in ["Vehicle", "Drug_A", "Drug_B"]:
        for rep in range(1, 5):
            for t in times:
                if treat == "Vehicle":
                    mu = 1.0 + 0.018 * t
                elif treat == "Drug_A":
                    mu = 1.0 + 1.2 * (1 - np.exp(-t / 10.0))
                else:  # Drug_B: rise then fall
                    mu = 1.0 + 1.1 * np.exp(-((t - 12) ** 2) / 120.0)
                rows.append({"time_hours": t, "treatment": treat, "replicate": f"R{rep}",
                             "signal": round(float(mu + rng.normal(0, 0.05)), 3),
                             "unit": "fold_change"})
    return pd.DataFrame(rows), None


def b_heatmap(rng):
    # 30 genes x 12 samples (Ctrl/DrugA/DrugB) z-scored, with block structure.
    samples = [f"{p}_{i}" for p in ["Ctrl", "DrugA", "DrugB"] for i in range(1, 5)]
    rows = []
    for g in range(1, 31):
        vals = rng.normal(0, 0.5, len(samples))
        if g <= 10:        # up in DrugA
            vals[4:8] += 1.5
        elif g <= 20:      # up in DrugB
            vals[8:12] += 1.5
        else:              # down in both drugs
            vals[4:12] -= 1.2
        row = {"gene": f"Gene_{g:02d}"}
        row.update({s: round(float(v), 3) for s, v in zip(samples, vals)})
        rows.append(row)
    return pd.DataFrame(rows), None


def b_volcano(rng):
    # 500 features differential expression results.
    n = 500
    lfc = rng.normal(0, 1.1, n)
    # spike in some strong up/down regulated genes
    lfc[:40] += rng.uniform(1.5, 4.0, 40)
    lfc[40:80] -= rng.uniform(1.5, 4.0, 40)
    # p-value smaller for larger |lfc|
    base = rng.uniform(0, 1, n)
    pval = np.clip(base * np.exp(-np.abs(lfc)), 1e-12, 1.0)
    adj = np.clip(pval * 5.0, 1e-12, 1.0)
    classes = rng.choice(["immune", "metabolic", "other"], n, p=[0.2, 0.2, 0.6])
    rows = []
    for i in range(n):
        sig = (abs(lfc[i]) >= 1.0) and (adj[i] <= 0.05)
        rows.append({"gene": f"GENE{i+1:04d}", "log2_fold_change": round(float(lfc[i]), 4),
                     "p_value": float(f"{pval[i]:.4e}"), "adjusted_p_value": float(f"{adj[i]:.4e}"),
                     "gene_class": classes[i],
                     "label": f"GENE{i+1:04d}" if sig and rng.random() < 0.3 else ""})
    return pd.DataFrame(rows), None


def b_enrichment(rng):
    terms = [
        ("Interferon gamma response", "Hallmark"), ("Oxidative phosphorylation", "Hallmark"),
        ("Epithelial migration", "GO_BP"), ("Cell cycle checkpoint", "Reactome"),
        ("Antigen processing", "GO_BP"), ("Complement cascade", "Reactome"),
        ("DNA repair", "Hallmark"), ("T cell activation", "GO_BP"),
        ("Apoptosis", "Hallmark"), ("mTOR signaling", "Reactome"),
        ("Extracellular matrix", "GO_CC"), ("Hypoxia", "Hallmark"),
    ]
    rows = []
    for term, cat in terms:
        ratio = float(rng.uniform(0.05, 0.35))
        count = int(rng.integers(20, 70))
        fdr = float(10 ** (-rng.uniform(1.5, 5.0)))
        rows.append({"term": term, "category": cat, "gene_ratio": round(ratio, 3),
                     "gene_count": count, "fdr": float(f"{fdr:.3e}"),
                     "neg_log10_fdr": round(float(-np.log10(fdr)), 3)})
    return pd.DataFrame(rows), None


def b_kaplan_meier(rng):
    # Survival times for low- vs high-risk groups (~30% censored).
    rows = []
    n = 0
    for grp, scale in [("Low_risk", 34.0), ("High_risk", 14.0)]:
        for _ in range(60):
            n += 1
            t = float(rng.exponential(scale))
            t = min(t, 60.0)
            censored = (t >= 60.0) or (rng.random() < 0.25)
            rows.append({"sample_id": f"{'Lo' if grp=='Low_risk' else 'Hi'}_{n:03d}",
                         "group": grp, "time_months": round(t, 2),
                         "event": 0 if censored else 1,
                         "censor_reason": "lost_to_followup" if censored else ""})
    return pd.DataFrame(rows), None


def b_stacked(rng):
    # Cell-type composition fractions per sample (sum to 1), two groups.
    cell_types = ["T_cell", "B_cell", "Myeloid", "Stromal", "Epithelial"]
    rows = []
    for i in range(1, 31):
        grp = "Control" if i <= 15 else "Treated"
        alpha = [3, 2, 2, 1.5, 1.5] if grp == "Control" else [2, 1.5, 3, 1.5, 2]
        fracs = rng.dirichlet(alpha)
        for ct, f in zip(cell_types, fracs):
            rows.append({"sample_id": f"S{i:02d}", "group": grp, "cell_type": ct,
                         "fraction": round(float(f), 4)})
    return pd.DataFrame(rows), None


def b_waterfall(rng):
    # Best % change in tumor size per patient (oncology waterfall).
    rows = []
    for i in range(1, 41):
        val = float(np.clip(rng.normal(-15, 35), -95, 60))
        cat = "PR" if val <= -30 else ("PD" if val >= 20 else "SD")
        rows.append({"patient_id": f"P{i:03d}", "treatment_arm": rng.choice(["Arm_A", "Arm_B"]),
                     "best_percent_change": round(val, 1), "response_category": cat,
                     "duration_months": round(float(rng.uniform(1, 18)), 1)})
    return pd.DataFrame(rows), None


def b_pca(rng):
    # Expression matrix (50 genes x 12 samples) + sample metadata.
    samples = [f"S{i:02d}" for i in range(1, 13)]
    groups = ["Control"] * 6 + ["Treated"] * 6
    batches = [f"Batch_{1 + (i % 2)}" for i in range(12)]
    mat = rng.normal(5.0, 0.8, (50, 12))
    # group separation on first 20 genes; mild batch effect
    for j in range(12):
        if groups[j] == "Treated":
            mat[:20, j] += 1.3
        if batches[j] == "Batch_2":
            mat[:, j] += 0.4
    matrix = pd.DataFrame(mat.round(3), columns=samples)
    matrix.insert(0, "gene", [f"Gene_{i:03d}" for i in range(1, 51)])
    meta = pd.DataFrame({
        "sample_id": samples, "group": groups, "batch": batches,
        "library_size_millions": [round(float(rng.uniform(20, 40)), 2) for _ in samples],
    })
    return matrix, meta


def b_oncoprint(rng):
    genes = ["TP53", "PIK3CA", "KRAS", "EGFR", "PTEN", "MYC", "BRAF", "APC", "ALK", "CDKN2A"]
    patients = [f"P{i:03d}" for i in range(1, 25)]
    alts = ["Missense", "Truncating", "Amplification", "Deletion", "Fusion"]
    rows = []
    for gi, gene in enumerate(genes):
        freq = 0.5 * (1 - gi / len(genes)) + 0.08   # higher genes mutated more often
        for pat in patients:
            if rng.random() < freq:
                a = rng.choice(alts, p=[0.45, 0.2, 0.15, 0.12, 0.08])
                rows.append({"patient_id": pat, "gene": gene, "alteration_type": a,
                             "variant_annotation": "p.X" if a in ("Missense", "Truncating") else a,
                             "variant_allele_fraction": round(float(rng.uniform(0.1, 0.9)), 2)
                             if a in ("Missense", "Truncating") else ""})
    return pd.DataFrame(rows), None


def b_lollipop(rng):
    types = ["Missense", "Nonsense", "Frameshift", "In_frame_del"]
    rows = []
    used = set()
    for _ in range(40):
        pos = int(rng.integers(20, 950))
        if pos in used:
            continue
        used.add(pos)
        mt = rng.choice(types, p=[0.6, 0.15, 0.15, 0.1])
        domain = "Kinase" if 300 <= pos <= 600 else ("SH2" if 700 <= pos <= 820 else "Other")
        rows.append({"gene": "GENE_X", "protein_position": pos,
                     "amino_acid_change": f"p.{rng.choice(list('ACDEFGHIKLMNPQRSTVWY'))}{pos}"
                                          f"{rng.choice(list('ACDEFGHIKLMNPQRSTVWY*'))}",
                     "mutation_type": mt, "sample_count": int(rng.integers(1, 12)),
                     "domain": domain})
    return pd.DataFrame(rows).sort_values("protein_position").reset_index(drop=True), None


def b_roc(rng):
    # Binary labels + scores from a strong model A and weaker model B.
    rows = []
    for i in range(1, 121):
        label = 0 if i <= 60 else 1
        cohort = "Discovery" if i % 2 == 0 else "Validation"
        a = float(np.clip(rng.normal(0.7 if label else 0.35, 0.13), 0, 1))
        b = float(np.clip(rng.normal(0.6 if label else 0.45, 0.18), 0, 1))
        rows.append({"sample_id": f"S{i:03d}", "true_label": label,
                     "score_model_a": round(a, 4), "score_model_b": round(b, 4),
                     "cohort": cohort})
    return pd.DataFrame(rows), None


def b_forest(rng):
    subgroups = ["All patients", "Age < 65", "Age >= 65", "Male", "Female",
                 "Biomarker high", "Biomarker low", "Prior therapy yes", "Prior therapy no"]
    rows = []
    for i, sg in enumerate(subgroups):
        hr = float(np.clip(rng.normal(1.0, 0.35), 0.3, 2.2))
        se = float(rng.uniform(0.12, 0.3))
        rows.append({"study": f"Study_{i+1}", "subgroup": sg,
                     "hazard_ratio": round(hr, 3),
                     "ci_low": round(hr * np.exp(-1.96 * se), 3),
                     "ci_high": round(hr * np.exp(1.96 * se), 3),
                     "p_value": round(float(rng.uniform(0.005, 0.4)), 4),
                     "n": int(rng.integers(80, 400))})
    return pd.DataFrame(rows), None


def b_ridge(rng):
    # Single-cell-like score distribution along pseudotime per condition.
    rows = []
    n = 0
    for cond, loc in [("Control", 0.35), ("Stimulated", 0.6), ("Inhibited", 0.25)]:
        for _ in range(350):
            n += 1
            pt = float(np.clip(rng.normal(loc, 0.18), 0, 1))
            rows.append({"cell_id": f"C{n:04d}",
                         "sample_id": f"{cond[:3]}_S{rng.integers(1,4)}",
                         "condition": cond, "pseudotime": round(pt, 4),
                         "score": round(float(rng.normal(3 + 2 * pt, 0.7)), 3)})
    return pd.DataFrame(rows), None


@dataclass
class Example:
    plot_type: str
    slug: str
    sheet: str          # Excel-safe (<=31 chars), unique
    use_case: str
    builder: Callable
    required_columns: List[str]
    optional_columns: List[str] = field(default_factory=list)
    replace_help: str = ""
    common_mistakes: List[str] = field(default_factory=list)
    aux_name: Optional[str] = None    # e.g. "metadata" for PCA


EXAMPLES: List[Example] = [
    Example("barplot_with_error_bar", "bar_error", "Bar_error",
            "Compare a mean readout across experimental conditions with replicate error bars.",
            b_bar_error, ["condition", "replicate", "measurement"], ["unit", "experiment_batch"],
            "Keep one row per replicate. Replace the condition labels and measurement values; "
            "the app computes the mean and SEM/SD/CI for you.",
            ["Do not pre-average — give raw replicate rows.",
             "Keep 'condition' as text, 'measurement' as numbers."]),
    Example("grouped_barplot_with_error_bar", "grouped_bar", "Grouped_bar",
            "Two-factor comparison (e.g. genotype x treatment) with grouped bars and error bars.",
            b_grouped_bar, ["genotype", "treatment", "replicate", "expression"], ["gene", "unit"],
            "One row per replicate. 'genotype' is the x-axis, 'treatment' is the grouping color.",
            ["Keep both grouping columns categorical (text)."]),
    Example("boxplot_or_violin_with_points", "box_violin", "Box_violin",
            "Show full distributions per group as box or violin plots with overlaid points.",
            b_box_violin, ["sample_id", "group", "value"], ["batch", "sex"],
            "One row per sample/observation. Switch box vs violin with the 'kind' option.",
            ["Use enough samples per group (>=5) for a meaningful distribution."]),
    Example("scatterplot_with_regression", "scatter", "Scatter",
            "Relationship between two continuous variables, colored by group, optional fit line.",
            b_scatter, ["sample_id", "x_marker", "y_response"], ["group", "label"],
            "x and y must be numeric. Leave 'label' blank for points you don't want annotated.",
            ["Blank labels are fine; non-numeric x/y will be dropped."]),
    Example("lineplot_timecourse_with_error_band", "line_timecourse", "Line_timecourse",
            "Mean response over time per treatment, with a shaded SEM/CI error band.",
            b_line_timecourse, ["time_hours", "treatment", "replicate", "signal"], ["unit"],
            "Long format: one row per time point per replicate. 'treatment' colors the lines.",
            ["Keep time numeric and data in long (not wide) format."]),
    Example("heatmap_clustered_matrix", "heatmap", "Heatmap",
            "Gene-by-sample expression matrix with optional row/column clustering.",
            b_heatmap, ["gene", "<sample columns>"], [],
            "First column = row label (gene). All other columns are numeric samples.",
            ["Keep the first column as labels; every other column must be numeric."]),
    Example("volcano_plot", "volcano", "Volcano",
            "Differential expression: log2 fold change vs significance, highlighting hits.",
            b_volcano, ["gene", "log2_fold_change", "p_value"],
            ["adjusted_p_value", "gene_class", "label"],
            "One row per gene/feature. Provide p_value (and adjusted_p_value if available).",
            ["p-values must be numeric (scientific notation is fine)."]),
    Example("enrichment_dotplot", "enrichment", "Enrichment_dot",
            "Pathway/term enrichment: dot size = gene count, color = significance.",
            b_enrichment, ["term", "gene_ratio", "fdr"], ["category", "gene_count", "neg_log10_fdr"],
            "One row per enriched term. Provide FDR (the app derives -log10 FDR if missing).",
            ["gene_ratio should be a fraction between 0 and 1."]),
    Example("kaplan_meier_survival_curve", "kaplan_meier", "Kaplan_Meier",
            "Survival probability over time by group, with censoring marks.",
            b_kaplan_meier, ["sample_id", "group", "time_months", "event"], ["censor_reason"],
            "One row per patient. event=1 means the event occurred; event=0 means censored.",
            ["Encode event as 1/0, not text."]),
    Example("stacked_bar_composition", "stacked", "Stacked_composition",
            "Cell-type (or category) composition per sample as stacked fractions.",
            b_stacked, ["sample_id", "cell_type", "fraction"], ["group"],
            "Long format: one row per sample per cell type. Fractions should sum to ~1 per sample.",
            ["Fractions per sample should add up to about 1.0."]),
    Example("waterfall_plot", "waterfall", "Waterfall",
            "Best percent change per patient (oncology response), sorted into a waterfall.",
            b_waterfall, ["patient_id", "best_percent_change"],
            ["treatment_arm", "response_category", "duration_months"],
            "One row per patient. Use negative values for tumor shrinkage.",
            ["best_percent_change must be numeric (can be negative)."]),
    Example("pca_scatter_from_matrix", "pca", "PCA",
            "PCA of an expression matrix; samples colored by group and shaped by batch.",
            b_pca, ["gene", "<sample columns>"], [],
            "Provide the matrix (genes x samples) as data, and a metadata table whose "
            "'sample_id' matches the matrix sample column names.",
            ["Metadata sample_id values must exactly match the matrix column headers."],
            aux_name="metadata"),
    Example("oncoprint_mutation_heatmap", "oncoprint", "Oncoprint",
            "Gene-by-sample alteration grid (oncoprint) colored by alteration type.",
            b_oncoprint, ["patient_id", "gene", "alteration_type"],
            ["variant_annotation", "variant_allele_fraction"],
            "One row per alteration (a patient/gene can appear multiple times).",
            ["alteration_type should use a small, consistent set of labels."]),
    Example("lollipop_mutation_plot", "lollipop", "Lollipop",
            "Mutation counts along a protein, as lollipops colored by mutation type.",
            b_lollipop, ["gene", "protein_position", "sample_count"],
            ["amino_acid_change", "mutation_type", "domain"],
            "One row per protein position. Positions and counts must be integers.",
            ["Use integer protein positions and counts."]),
    Example("roc_curve", "roc", "ROC",
            "ROC curves with AUC comparing one or two classifier scores.",
            b_roc, ["sample_id", "true_label", "score_model_a"], ["score_model_b", "cohort"],
            "true_label is 1 for the positive class, 0 for negative. Scores are continuous.",
            ["Include both classes (some 1s and some 0s)."]),
    Example("forest_plot", "forest", "Forest",
            "Subgroup effect sizes (hazard/odds ratios) with confidence intervals.",
            b_forest, ["subgroup", "hazard_ratio", "ci_low", "ci_high"], ["study", "p_value", "n"],
            "One row per subgroup. Provide the estimate and its CI bounds.",
            ["ci_low must be <= estimate <= ci_high."]),
    Example("ridge_or_density_plot", "ridge", "Ridgeline",
            "Stacked density (ridgeline) distributions of a value per condition.",
            b_ridge, ["cell_id", "condition", "pseudotime"], ["sample_id", "score"],
            "One row per observation. The x value (pseudotime/score) must be numeric.",
            ["Provide many rows per group for smooth densities."]),
]


def _write_table(df: pd.DataFrame, base: str):
    df.to_csv(base + ".csv", index=False)
    df.to_csv(base + ".tsv", sep="\t", index=False)
    with pd.ExcelWriter(base + ".xlsx", engine="openpyxl") as xw:
        df.to_excel(xw, index=False, sheet_name="data")


def _readme(ex: Example, manifest_entry: Dict[str, Any]) -> str:
    req = "\n".join(f"  - `{c}`" for c in ex.required_columns)
    opt = "\n".join(f"  - `{c}`" for c in ex.optional_columns) or "  - (none)"
    mistakes = "\n".join(f"  - {m}" for m in ex.common_mistakes) or "  - (none)"
    aux = ""
    if ex.aux_name:
        aux = ("\n## Auxiliary table\n\n"
               f"This plot also needs `metadata.csv` (sample metadata). Its `sample_id` "
               "values must match the sample column names in `data.*`.\n")
    return f"""# {display_name(ex.plot_type)} — example data

**Plot type id:** `{ex.plot_type}`

**Scientific use case:** {ex.use_case}

> ⚠️ **Synthetic data.** This dataset was generated by
> `scripts/generate_example_data.py` (seed {SEED}). It is plausible but NOT real
> and must not be cited as a biological finding. License: {LICENSE}.

## What a row represents

One row = one {('replicate/observation' if 'replicate' in ex.required_columns or 'sample_id' in ex.required_columns else 'record')} for this analysis.

## Columns

- **Required:**
{req}
- **Optional:**
{opt}
{aux}
## Files

- `data.csv`, `data.tsv`, `data.xlsx` — the same table in three formats.
- `plotspec.json` — a ready-to-use PlotSpec (plot type, column mapping, style, output).
- Open any of these in the app via **Use example data → {display_name(ex.plot_type)}**.

## Replace with your own data

{ex.replace_help}

Keep the **required column names** above (or remap columns in the app). Column
order does not matter — the app validates by name and type.

## Common mistakes to avoid

{mistakes}
"""


def main() -> int:
    os.makedirs(BY_PLOT_DIR, exist_ok=True)
    manifest: Dict[str, Any] = {
        "project": "make_my_figure",
        "generated_by": SOURCE,
        "seed": SEED,
        "data_type": "synthetic",
        "license": LICENSE,
        "note": ("All example datasets are synthetic. Published papers/figures are used only "
                 "as visual style references (layout, typography, panels, legends), never as a "
                 "source of copied data. Do not cite these examples as real findings."),
        "combined_workbook": os.path.relpath(COMBINED_XLSX, _ROOT),
        "plot_types": [],
    }
    combined_sheets: List[Tuple[str, pd.DataFrame]] = []

    rng_master = np.random.default_rng(SEED)
    for i, ex in enumerate(EXAMPLES):
        rng = np.random.default_rng(SEED + i)  # per-plot reproducible stream
        df, aux = ex.builder(rng)
        folder = os.path.join(BY_PLOT_DIR, ex.slug)
        os.makedirs(folder, exist_ok=True)
        base = os.path.join(folder, "data")
        _write_table(df, base)
        if aux is not None and ex.aux_name:
            _write_table(aux, os.path.join(folder, ex.aux_name))

        # PlotSpec JSON
        mapping = default_mapping(ex.plot_type)
        spec: Dict[str, Any] = {
            "plot_type": ex.plot_type,
            "input_table": "data.csv",
            "mapping": mapping,
            "journal_style": "nature_like",
            "output": {"formats": ["svg", "png", "pdf"], "width_mm": 89, "height_mm": 70, "dpi": 300},
            "layout": {"column_width": "single"},
        }
        if ex.aux_name:
            spec["aux_tables"] = {ex.aux_name: f"{ex.aux_name}.csv"}
        with open(os.path.join(folder, "plotspec.json"), "w", encoding="utf-8") as fh:
            json.dump(spec, fh, indent=2)

        rel = os.path.relpath(folder, _ROOT)
        entry = {
            "plot_type": ex.plot_type,
            "name": display_name(ex.plot_type),
            "slug": ex.slug,
            "description": ex.use_case,
            "use_case": ex.use_case,
            "required_columns": ex.required_columns,
            "optional_columns": ex.optional_columns,
            "files": {
                "csv": f"{rel}/data.csv", "tsv": f"{rel}/data.tsv",
                "xlsx": f"{rel}/data.xlsx", "plotspec": f"{rel}/plotspec.json",
                "readme": f"{rel}/README.md",
            },
            "aux_tables": ({ex.aux_name: f"{rel}/{ex.aux_name}.csv"} if ex.aux_name else {}),
            "excel_sheet": ex.sheet,
            "recommended_style_profiles": STYLES,
            "compatible_renderers": [ex.plot_type],
            "expected_export_formats": ["svg", "png", "pdf", "plot_spec.json"],
            "data_type": "synthetic",
            "source": SOURCE,
            "license": LICENSE,
            "provenance": "Synthetic; not derived from any published dataset.",
            "n_rows": int(len(df)),
            "user_replacement_note": ex.replace_help,
            "common_mistakes": ex.common_mistakes,
        }
        manifest["plot_types"].append(entry)

        with open(os.path.join(folder, "README.md"), "w", encoding="utf-8") as fh:
            fh.write(_readme(ex, entry))

        combined_sheets.append((ex.sheet, df))
        if aux is not None and ex.aux_name:
            combined_sheets.append((f"{ex.sheet[:24]}_meta"[:31], aux))
        print(f"  {ex.plot_type}: {len(df)} rows -> {rel}")

    # Combined workbook (one sheet per plot type, plus pca metadata sheet).
    with pd.ExcelWriter(COMBINED_XLSX, engine="openpyxl") as xw:
        used = set()
        for name, df in combined_sheets:
            sheet = name[:31]
            while sheet in used:
                sheet = (sheet[:29] + "_2")[:31]
            used.add(sheet)
            df.to_excel(xw, index=False, sheet_name=sheet)

    with open(MANIFEST_PATH, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    print(f"\nWrote {len(EXAMPLES)} example datasets to {os.path.relpath(BY_PLOT_DIR, _ROOT)}")
    print(f"Combined workbook: {os.path.relpath(COMBINED_XLSX, _ROOT)}")
    print(f"Manifest: {os.path.relpath(MANIFEST_PATH, _ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
