"""Generate the bundled example datasets for the spatial plot types.

Five of the six are synthetic, matching the project's existing example-data
policy (CC0, generated from a fixed seed, never copied from a publication).
They are shaped to look like the real platforms — Visium-style spots, Xenium-
style cells and transcripts — so the columns a user meets here are the columns
they will meet in their own export.

The sixth, the neighbourhood enrichment matrix, uses the *real published
values* from CNTools S1 Data (Tao et al. 2024, PLOS Comput Biol, CC BY 4.0),
which is redistributable with attribution. A user rendering that example is
reproducing a published figure panel, not a simulation of one.

    python scripts/generate_spatial_example_data.py
"""
from __future__ import annotations

import json
import os
import shutil

import numpy as np
import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BY_TYPE = os.path.join(ROOT, "examples", "by_plot_type")
MANIFEST = os.path.join(ROOT, "examples", "example_data_manifest.json")
SEED = 42

CELL_TYPES = ["Tumor", "Stroma", "Macrophage", "CD8 T cell", "CD4 T cell",
              "B cell", "Endothelial", "Fibroblast"]


def _tissue(rng, n, cx, cy, radius):
    ang = rng.uniform(0, 2 * np.pi, n)
    rad = np.sqrt(rng.uniform(0, 1, n)) * radius
    return cx + rad * np.cos(ang), cy + rad * np.sin(ang)


def _cells(rng, n=2400):
    """Xenium-style cells: a tumour core, an immune rim and scattered stroma."""
    x, y = _tissue(rng, n, 1500.0, 1200.0, 900.0)
    d = np.sqrt((x - 1250) ** 2 + (y - 1050) ** 2)
    p = np.zeros((n, len(CELL_TYPES)))
    core = np.clip(1.0 - d / 700.0, 0, 1)
    p[:, 0] = 0.10 + 0.75 * core                      # Tumor
    p[:, 1] = 0.20 * (1 - core) + 0.05                # Stroma
    p[:, 2] = 0.22 * np.exp(-((d - 620) ** 2) / 32000) + 0.04
    p[:, 3] = 0.20 * np.exp(-((d - 680) ** 2) / 26000) + 0.03
    p[:, 4] = 0.14 * np.exp(-((d - 700) ** 2) / 30000) + 0.03
    p[:, 5] = 0.10 * np.exp(-((d - 780) ** 2) / 18000) + 0.02
    p[:, 6] = 0.05 + 0.04 * (1 - core)
    p[:, 7] = 0.16 * (1 - core) + 0.04
    p /= p.sum(axis=1, keepdims=True)
    ct = [CELL_TYPES[i] for i in (p.cumsum(1) > rng.uniform(size=(n, 1))).argmax(1)]

    # A marker that tracks the tumour core, and one that tracks the immune rim.
    epcam = np.clip(rng.gamma(2.0, 1.1, n) + 9.0 * core, 0, None)
    cd8 = np.clip(rng.gamma(1.4, 0.8, n) + 6.0 * np.exp(-((d - 680) ** 2) / 26000), 0, None)
    return pd.DataFrame({
        "cell_id": [f"cell_{i:05d}" for i in range(n)],
        "x": np.round(x, 2), "y": np.round(y, 2),
        "cell_type": ct, "sample": "Section_1",
        "EPCAM": np.round(epcam, 3), "CD8A": np.round(cd8, 3),
    })


def _write(slug, df, entry, aux=None, readme=""):
    d = os.path.join(BY_TYPE, slug)
    os.makedirs(d, exist_ok=True)
    df.to_csv(os.path.join(d, "data.csv"), index=False)
    df.to_csv(os.path.join(d, "data.tsv"), sep="\t", index=False)
    with pd.ExcelWriter(os.path.join(d, "data.xlsx")) as xw:
        df.to_excel(xw, sheet_name="data", index=False)
        for name, adf in (aux or {}).items():
            adf.to_excel(xw, sheet_name=name[:31], index=False)
    for name, adf in (aux or {}).items():
        adf.to_csv(os.path.join(d, f"{name}.csv"), index=False)
    with open(os.path.join(d, "plotspec.json"), "w", encoding="utf-8") as fh:
        json.dump(entry.pop("_plotspec"), fh, indent=2)
    with open(os.path.join(d, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(readme)
    return entry


def main() -> int:
    rng = np.random.default_rng(SEED)
    cells = _cells(rng)
    entries = []

    def spec(plot_type, mapping, spatial, title):
        return {"plot_type": plot_type, "input_table": "data.csv", "mapping": mapping,
                "journal_style": "publication", "layout": {"title": title},
                "spatial": spatial,
                "output": {"formats": ["png", "pdf", "svg"], "dpi": 300,
                           "width_mm": 180, "height_mm": 150}}

    def files(slug, aux=()):
        f = {k: f"examples/by_plot_type/{slug}/data.{k}" for k in ("csv", "tsv", "xlsx")}
        f["plotspec"] = f"examples/by_plot_type/{slug}/plotspec.json"
        f["readme"] = f"examples/by_plot_type/{slug}/README.md"
        return f

    common = dict(recommended_style_profiles=["publication"],
                  expected_export_formats=["svg", "png", "pdf", "plot_spec.json"],
                  data_type="synthetic", license="CC0-1.0",
                  source="generated by scripts/generate_spatial_example_data.py",
                  provenance="Synthetic; not derived from any published dataset.")

    # ---------------- 1. categorical map ----------------------------------
    slug = "spatial_categorical"
    e = dict(plot_type="spatial_categorical_map", name="Spatial map (categories)", slug=slug,
             description="Cells positioned in tissue coordinates and coloured by cell type.",
             use_case="Show where each cell type sits in a tissue section.",
             required_columns=["x", "y", "cell_type"],
             optional_columns=["cell_id", "sample", "EPCAM", "CD8A"],
             files=files(slug), aux_tables={}, excel_sheet="Spatial_categorical",
             compatible_renderers=["spatial_categorical_map"], n_rows=int(len(cells)),
             user_replacement_note=("One row per cell or spot. Replace x/y with your "
                                    "coordinates and cell_type with your labels. Declare the "
                                    "coordinate units — a scale bar is only drawn when they "
                                    "are physical."),
             common_mistakes=["Do not mix sections in one table without a sample column — "
                              "neighbours are never computed across samples.",
                              "Image coordinates run y-downward: set orientation='y_down' "
                              "rather than flipping y by hand."],
             **common)
    e["_plotspec"] = spec("spatial_categorical_map",
                          {"x": "x", "y": "y", "category": "cell_type"},
                          {"coordinate_units": "micrometre", "orientation": "y_up",
                           "scale_bar": True, "marker_size": 5, "alpha": 0.9},
                          "Cell types in tissue")
    entries.append(_write(slug, cells, e, readme=(
        "# Spatial map (categories)\n\nOne row per cell. `x`/`y` are tissue coordinates in "
        "micrometres, `cell_type` is the label drawn in colour.\n\nSynthetic data (CC0), "
        "generated with seed 42 to resemble a tumour core with an immune rim.\n\n"
        "Declare `coordinate_units`; with `arbitrary` units no scale bar is drawn, because a "
        "bar would assert a physical length the data does not carry.\n")))

    # ---------------- 2. feature map --------------------------------------
    slug = "spatial_feature"
    e = dict(plot_type="spatial_feature_map", name="Spatial map (continuous value)", slug=slug,
             description="Cells coloured by a continuous value such as marker expression.",
             use_case="Show where a gene or marker is expressed across a section.",
             required_columns=["x", "y", "EPCAM"],
             optional_columns=["cell_id", "cell_type", "sample", "CD8A"],
             files=files(slug), aux_tables={}, excel_sheet="Spatial_feature",
             compatible_renderers=["spatial_feature_map"], n_rows=int(len(cells)),
             user_replacement_note=("Replace EPCAM with your own measurement column. Nothing "
                                    "is transformed unless you ask: set spatial.transform "
                                    "explicitly and the colourbar label follows it."),
             common_mistakes=["Do not pre-log the values and leave the label saying "
                              "'expression' — set spatial.transform so the colourbar is "
                              "labelled correctly.",
                              "log2/log10 need strictly positive values; use log1p/log2p1 "
                              "when zeros are expected."],
             **common)
    e["_plotspec"] = spec("spatial_feature_map", {"x": "x", "y": "y", "value": "EPCAM"},
                          {"coordinate_units": "micrometre", "scale_bar": True,
                           "marker_size": 6, "transform": "none"},
                          "EPCAM expression")
    entries.append(_write(slug, cells, e, readme=(
        "# Spatial map (continuous value)\n\nSame cell table as the categorical example; "
        "`EPCAM` tracks the tumour core and `CD8A` the immune rim.\n\n"
        "No transform, normalisation or clipping is applied unless the spec names it, and "
        "whatever is applied is written into the colourbar label.\n")))

    # ---------------- 3. transcript map -----------------------------------
    genes = ["EPCAM", "CD8A", "COL1A1", "MS4A1", "PECAM1"]
    rows = []
    for gi, g in enumerate(genes):
        # Kept deliberately modest: bundled examples ship inside every installer,
        # and this still reads as a dense transcript map.
        n = [2200, 1100, 1500, 600, 700][gi]
        if g == "EPCAM":
            tx, ty = _tissue(rng, n, 1250.0, 1050.0, 560.0)
        elif g == "CD8A":
            a = rng.uniform(0, 2 * np.pi, n); r = 680 + rng.normal(0, 70, n)
            tx, ty = 1250 + r * np.cos(a), 1050 + r * np.sin(a)
        elif g == "MS4A1":
            a = rng.uniform(0, 2 * np.pi, n); r = 790 + rng.normal(0, 60, n)
            tx, ty = 1250 + r * np.cos(a), 1050 + r * np.sin(a)
        else:
            tx, ty = _tissue(rng, n, 1500.0, 1200.0, 900.0)
        rows.append(pd.DataFrame({"transcript_id": [f"t_{g}_{i:06d}" for i in range(n)],
                                  "x": np.round(tx, 2), "y": np.round(ty, 2), "gene": g,
                                  "qv": np.round(rng.uniform(20, 40, n), 2)}))
    tx_df = pd.concat(rows, ignore_index=True).sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    slug = "spatial_transcript"
    e = dict(plot_type="spatial_transcript_map", name="Spatial transcript map", slug=slug,
             description="Individual transcript detections coloured by gene.",
             use_case="Show where transcripts of selected genes were detected in a section.",
             required_columns=["x", "y", "gene"], optional_columns=["transcript_id", "qv"],
             files=files(slug), aux_tables={}, excel_sheet="Spatial_transcript",
             compatible_renderers=["spatial_transcript_map"], n_rows=int(len(tx_df)),
             user_replacement_note=("One row per detected transcript. Use spatial.genes to "
                                    "choose which to draw and spatial.min_quality to filter "
                                    "on a score column; both are recorded in the figure "
                                    "metadata."),
             common_mistakes=["Transcript tables are not cell tables — one row is one "
                              "detection, not one cell.",
                              "Nothing is subsampled automatically; set spatial.max_points "
                              "if you want a recorded subsample."],
             **common)
    e["_plotspec"] = spec("spatial_transcript_map", {"x": "x", "y": "y", "gene": "gene",
                                                     "quality": "qv"},
                          {"coordinate_units": "micrometre", "scale_bar": True,
                           "marker_size": 1.2, "alpha": 0.55}, "Transcripts by gene")
    entries.append(_write(slug, tx_df, e, readme=(
        "# Spatial transcript map\n\nOne row per transcript detection (Xenium-style): "
        f"{len(tx_df):,} rows across {len(genes)} genes, with a `qv` quality score.\n\n"
        "Dense marks are rasterised inside PDF/SVG while text and axes stay vector, so the "
        "file stays openable. Subsampling never happens on its own.\n")))

    # ---------------- 4. ROI polygons -------------------------------------
    roi_rows = []
    for name, (cx, cy, rr, cat) in {
        "ROI_1": (1250, 1050, 520, "Tumor core"),
        "ROI_2": (1980, 1500, 330, "Invasive front"),
        "ROI_3": (900, 1750, 300, "Immune aggregate"),
    }.items():
        k = 22
        a = np.linspace(0, 2 * np.pi, k, endpoint=False)
        r = rr * (1 + 0.10 * np.sin(3 * a) + rng.normal(0, 0.015, k))
        for i in range(k):
            roi_rows.append({"roi_id": name, "vertex_order": i,
                             "x": round(float(cx + r[i] * np.cos(a[i])), 2),
                             "y": round(float(cy + r[i] * np.sin(a[i])), 2),
                             "roi_label": name, "roi_category": cat})
    roi_df = pd.DataFrame(roi_rows)
    slug = "spatial_roi"
    e = dict(plot_type="spatial_roi_map", name="Spatial ROI / region outlines", slug=slug,
             description="Regions of interest drawn as labelled polygon outlines.",
             use_case="Outline and label anatomical or analytical regions on a section.",
             required_columns=["roi_id", "x", "y"],
             optional_columns=["vertex_order", "roi_label", "roi_category"],
             files=files(slug), aux_tables={}, excel_sheet="Spatial_roi",
             compatible_renderers=["spatial_roi_map"], n_rows=int(len(roi_df)),
             user_replacement_note=("One row per polygon vertex. Keep vertex_order so the "
                                    "outline is traced in the right sequence; a repeated "
                                    "closing vertex is fine."),
             common_mistakes=["Unordered vertices produce a self-crossing outline — keep "
                              "vertex_order.",
                              "An ROI with fewer than three vertices is reported and skipped, "
                              "not silently dropped."],
             **common)
    e["_plotspec"] = spec("spatial_roi_map",
                          {"roi": "roi_id", "x": "x", "y": "y", "vertex_order": "vertex_order",
                           "roi_label": "roi_label", "roi_category": "roi_category"},
                          {"coordinate_units": "micrometre", "scale_bar": True,
                           "roi_fill_alpha": 0.12, "roi_linewidth": 1.6},
                          "Regions of interest")
    entries.append(_write(slug, roi_df, e, readme=(
        "# Spatial ROI / region outlines\n\nOne row per polygon vertex, ordered by "
        "`vertex_order`. Three ROIs with category labels.\n\nImporting geometry someone else "
        "defined is the supported path; there is no freehand drawing tool, because a "
        "reproducible ROI is one that came from a recorded definition.\n")))

    # ---------------- 5. composition glyphs -------------------------------
    gx, gy = np.meshgrid(np.linspace(700, 2300, 9), np.linspace(500, 1900, 8))
    gx, gy = gx.ravel(), gy.ravel()
    comp = []
    for i, (sx, sy) in enumerate(zip(gx, gy)):
        d = np.sqrt((sx - 1250) ** 2 + (sy - 1050) ** 2)
        core = float(np.clip(1 - d / 750.0, 0, 1))
        w = np.array([0.08 + 0.72 * core, 0.22 * (1 - core) + 0.05,
                      0.18 * np.exp(-((d - 620) ** 2) / 40000) + 0.05,
                      0.16 * np.exp(-((d - 680) ** 2) / 30000) + 0.04,
                      0.06 + 0.10 * (1 - core), 0.05 + 0.05 * (1 - core),
                      0.04 + 0.03 * (1 - core), 0.14 * (1 - core) + 0.04])
        w = w / w.sum()
        for ct, f in zip(CELL_TYPES, w):
            comp.append({"spot_id": f"spot_{i:03d}", "x": round(float(sx), 1),
                         "y": round(float(sy), 1), "cell_type": ct,
                         "fraction": round(float(f), 5)})
    comp_df = pd.DataFrame(comp)
    slug = "spatial_composition"
    e = dict(plot_type="spatial_composition_map", name="Spatial composition glyphs", slug=slug,
             description="Cell-type composition per spot drawn as pie glyphs in tissue space.",
             use_case="Show deconvolved cell-type mixtures at Visium-style spots.",
             required_columns=["spot_id", "x", "y", "cell_type", "fraction"],
             optional_columns=[], files=files(slug), aux_tables={},
             excel_sheet="Spatial_composition",
             compatible_renderers=["spatial_composition_map"], n_rows=int(len(comp_df)),
             user_replacement_note=("Long form: one row per spot and category. Counts work "
                                    "too — set spatial.normalize='fraction' to convert them."),
             common_mistakes=["Fractions that do not sum to 1 are reported, not rescaled — a "
                              "short sum usually means a missing category.",
                              "Use top_k or min_fraction to merge rare categories into "
                              "'Other' rather than drawing unreadable slivers."],
             **common)
    e["_plotspec"] = spec("spatial_composition_map",
                          {"spot": "spot_id", "x": "x", "y": "y",
                           "category": "cell_type", "value": "fraction"},
                          {"coordinate_units": "micrometre", "normalize": "fraction",
                           "scale_bar": True, "donut_hole": 0.0},
                          "Cell-type composition per spot")
    entries.append(_write(slug, comp_df, e, readme=(
        "# Spatial composition glyphs\n\nOne row per (spot, cell type) with a fraction; "
        "72 spots on a grid. Each spot is drawn as a pie of its mixture.\n\n"
        "Normalisation is explicit: with `normalize='as_given'` the fractions are drawn "
        "exactly as supplied and a short sum is reported rather than rescaled away.\n")))

    # ---------------- 6. enrichment matrix (REAL published values) --------
    src = os.path.join(ROOT, "benchmarks", "spatial_validation", "cntools_2024",
                       "derived", "neighborhood_enrichment_cntools.csv")
    slug = "neighborhood_enrichment"
    if os.path.exists(src):
        enr = pd.read_csv(src)
        enr["cell_type"] = ["CT_%02d" % c for c in enr["cell_type_index"]]
        enr = enr[["neighborhood", "cell_type", "enrichment_score",
                   "cell_type_frequency_in_neighborhood"]]
        lic = dict(data_type="published",
                   license="CC BY 4.0",
                   source=("CNTools S1 Data, Tao et al. 2024, PLOS Comput Biol 20(8):e1012344, "
                           "doi:10.1371/journal.pcbi.1012344"),
                   provenance=("Published Fig 3A (CRC, CC*) values, tidied by "
                               "benchmarks/spatial_validation/cntools_2024. Reproduced from "
                               "the deposited CRC data to 7.8e-14 max absolute difference."))
        e = dict(plot_type="neighborhood_enrichment_matrix",
                 name="Cellular-neighbourhood enrichment matrix", slug=slug,
                 description=("Cell-type enrichment across cellular neighbourhoods; colour is "
                              "the enrichment score, point area the frequency within the "
                              "neighbourhood."),
                 use_case="Show which cell types are enriched in which neighbourhoods.",
                 required_columns=["neighborhood", "cell_type", "enrichment_score"],
                 optional_columns=["cell_type_frequency_in_neighborhood"],
                 files=files(slug), aux_tables={}, excel_sheet="Neighborhood_enrichment",
                 recommended_style_profiles=["publication"],
                 expected_export_formats=["svg", "png", "pdf", "plot_spec.json"],
                 compatible_renderers=["neighborhood_enrichment_matrix"], n_rows=int(len(enr)),
                 user_replacement_note=("Produced by make_my_figure_core.spatial."
                                        "ct_cn_enrichment from your own cells; the renderer "
                                        "plots these values and never recomputes them."),
                 common_mistakes=["Enrichment is a log ratio: zero means 'as expected', so "
                                  "the colour scale is centred on zero by default.",
                                  "A dot matrix is unreadable without a size key — keep "
                                  "size_legend on."],
                 **lic)
        e["_plotspec"] = spec("neighborhood_enrichment_matrix",
                              {"neighborhood": "neighborhood", "cell_type": "cell_type",
                               "enrichment": "enrichment_score",
                               "frequency": "cell_type_frequency_in_neighborhood"},
                              {"cmap": "RdBu_r", "center": 0.0,
                               "colorbar_label": "Enrichment score"},
                              "Cell-type enrichment across neighbourhoods")
        entries.append(_write(slug, enr, e, readme=(
            "# Cellular-neighbourhood enrichment matrix\n\n**Real published data.** These are "
            "the Fig 3A (CRC, CC*) values from CNTools — Tao et al. 2024, *PLOS Computational "
            "Biology* 20(8):e1012344, doi:10.1371/journal.pcbi.1012344 — redistributed under "
            "CC BY 4.0.\n\n9 neighbourhoods x 28 cell types. Colour is the enrichment score, "
            "point area the cell type's frequency within the neighbourhood.\n\n"
            "Cell types are shown as `CT_00`..`CT_27` because the published spreadsheet does "
            "not label its columns. `benchmarks/spatial_validation/cntools_2024` reproduces "
            "these values from the deposited CRC data to a maximum absolute difference of "
            "7.8e-14.\n")))
    else:
        print(f"warning: {src} not found; skipping the enrichment example")

    # ---------------- manifest -------------------------------------------
    with open(MANIFEST, encoding="utf-8") as fh:
        manifest = json.load(fh)
    existing = {e["plot_type"] for e in manifest["plot_types"]}
    added = [e for e in entries if e["plot_type"] not in existing]
    manifest["plot_types"] = [e for e in manifest["plot_types"]
                              if e["plot_type"] not in {x["plot_type"] for x in entries}]
    manifest["plot_types"].extend(entries)
    manifest["note"] = (
        "Example datasets are synthetic unless an entry says otherwise. Published "
        "papers/figures are used as visual style references, never as a source of copied "
        "data — with one deliberate exception: the neighbourhood enrichment example carries "
        "real published values from CNTools S1 Data (CC BY 4.0, attributed in its entry and "
        "README), so that a user can render an actual published panel. Do not cite the "
        "synthetic examples as real findings.")
    with open(MANIFEST, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")
    print(f"wrote {len(entries)} spatial example datasets "
          f"({len(added)} new); manifest now has {len(manifest['plot_types'])} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
