"""Reproducible generator for Make My Figure example/template datasets.

Creates, for every plot type the app supports, a clean *synthetic* dataset plus
a CSV/TSV/XLSX copy, a PlotSpec JSON, and a README — under
``examples/by_plot_type/<slug>/`` — a combined workbook, and a machine-readable
manifest.

IMPORTANT: All bundled example data are SYNTHETIC (generated here with a fixed
seed). They look scientifically plausible but are NOT real measurements and must
not be cited as biological findings. Published papers/figures are used by this
project only as visual style references (layout, typography, panels, legends) —
never as a source of copied data.

Safe to re-run: it only writes inside ``examples/``.

Usage:
    python scripts/generate_example_data.py
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from make_my_figure_core.plots.registry import default_mapping, display_name  # noqa: E402

SEED = 42
EXAMPLES_DIR = os.path.join(_ROOT, "examples")
BY_PLOT_DIR = os.path.join(EXAMPLES_DIR, "by_plot_type")
COMBINED_XLSX = os.path.join(EXAMPLES_DIR, "Make_My_Figure_All_Example_Data.xlsx")
MANIFEST_PATH = os.path.join(EXAMPLES_DIR, "example_data_manifest.json")

LICENSE = "CC0-1.0"
SOURCE = "generated by scripts/generate_example_data.py"
STYLES = ["nature_like", "science_like", "cell_like"]


# ---------------------------------------------------------------------------
# Builders — each returns (primary_df, aux_df_or_None). Synthetic biology is
# described in the comments and in each example's README.
# ---------------------------------------------------------------------------
def b_bar_error(rng):
    # qPCR-like relative signal across 4 treatment conditions, 6 replicates each.
    conditions = ["Control", "Drug_A", "Drug_B", "Combination"]
    means = {"Control": 1.0, "Drug_A": 1.6, "Drug_B": 0.7, "Combination": 2.1}
    rows = []
    for cond in conditions:
        for i in range(1, 7):
            rows.append({
                "condition": cond,
                "replicate": f"R{i}",
                "measurement": round(float(rng.normal(means[cond], 0.12)), 3),
                "unit": "relative_signal",
                "experiment_batch": f"Batch_{1 + (i - 1) % 2}",
            })
    return pd.DataFrame(rows), None


def b_grouped_bar(rng):
    # Gene expression by genotype x treatment (two-factor), 5 replicates.
    base = {("WT", "Vehicle"): 1.0, ("WT", "Stimulus"): 1.8,
            ("KO", "Vehicle"): 0.8, ("KO", "Stimulus"): 1.2}
    rows = []
    for geno in ["WT", "KO"]:
        for treat in ["Vehicle", "Stimulus"]:
            for i in range(1, 6):
                rows.append({
                    "genotype": geno, "treatment": treat, "replicate": f"R{i}",
                    "expression": round(float(rng.normal(base[(geno, treat)], 0.1)), 3),
                    "gene": "IL6", "unit": "relative_mRNA",
                })
    return pd.DataFrame(rows), None


def b_box_violin(rng):
    # Biomarker level across three clinical groups, ~24 samples each.
    groups = {"Healthy": 4.5, "Disease": 6.2, "Treated": 5.2}
    rows = []
    n = 0
    for grp, mu in groups.items():
        for _ in range(24):
            n += 1
            rows.append({
                "sample_id": f"S{n:03d}", "group": grp,
                "value": round(float(rng.normal(mu, 0.6)), 3),
                "batch": f"Batch_{rng.integers(1, 4)}",
                "sex": rng.choice(["M", "F"]),
            })
    return pd.DataFrame(rows), None


def b_scatter(rng):
    # Two response groups with different marker-vs-response slopes.
    rows = []
    n = 0
    for grp, slope, intercept, count in [("Responder", 1.4, 1.0, 35),
                                         ("Non_responder", 0.5, 3.0, 25)]:
        for _ in range(count):
            n += 1
            x = float(rng.uniform(1, 9))
            y = slope * x + intercept + float(rng.normal(0, 1.0))
            rows.append({"sample_id": f"S{n:03d}", "x_marker": round(x, 3),
                         "y_response": round(y, 3), "group": grp,
                         "label": f"S{n:03d}" if rng.random() < 0.08 else ""})
    return pd.DataFrame(rows), None


def b_line_timecourse(rng):
    # Signal over time for three treatments, 4 replicates each.
    times = [0, 2, 4, 8, 12, 24, 48]
    rows = []
    for treat in ["Vehicle", "Drug_A", "Drug_B"]:
        for rep in range(1, 5):
            for t in times:
                if treat == "Vehicle":
                    mu = 1.0 + 0.018 * t
                elif treat == "Drug_A":
                    mu = 1.0 + 1.2 * (1 - np.exp(-t / 10.0))
                else:  # Drug_B: rise then fall
                    mu = 1.0 + 1.1 * np.exp(-((t - 12) ** 2) / 120.0)
                rows.append({"time_hours": t, "treatment": treat, "replicate": f"R{rep}",
                             "signal": round(float(mu + rng.normal(0, 0.05)), 3),
                             "unit": "fold_change"})
    return pd.DataFrame(rows), None


def b_heatmap(rng):
    # 30 genes x 12 samples (Ctrl/DrugA/DrugB) z-scored, with block structure.
    samples = [f"{p}_{i}" for p in ["Ctrl", "DrugA", "DrugB"] for i in range(1, 5)]
    rows = []
    for g in range(1, 31):
        vals = rng.normal(0, 0.5, len(samples))
        if g <= 10:        # up in DrugA
            vals[4:8] += 1.5
        elif g <= 20:      # up in DrugB
            vals[8:12] += 1.5
        else:              # down in both drugs
            vals[4:12] -= 1.2
        row = {"gene": f"Gene_{g:02d}"}
        row.update({s: round(float(v), 3) for s, v in zip(samples, vals)})
        rows.append(row)
    return pd.DataFrame(rows), None


def b_volcano(rng):
    # 500 features differential expression results.
    n = 500
    lfc = rng.normal(0, 1.1, n)
    # spike in some strong up/down regulated genes
    lfc[:40] += rng.uniform(1.5, 4.0, 40)
    lfc[40:80] -= rng.uniform(1.5, 4.0, 40)
    # p-value smaller for larger |lfc|
    base = rng.uniform(0, 1, n)
    pval = np.clip(base * np.exp(-np.abs(lfc)), 1e-12, 1.0)
    adj = np.clip(pval * 5.0, 1e-12, 1.0)
    classes = rng.choice(["immune", "metabolic", "other"], n, p=[0.2, 0.2, 0.6])
    rows = []
    for i in range(n):
        sig = (abs(lfc[i]) >= 1.0) and (adj[i] <= 0.05)
        rows.append({"gene": f"GENE{i+1:04d}", "log2_fold_change": round(float(lfc[i]), 4),
                     "p_value": float(f"{pval[i]:.4e}"), "adjusted_p_value": float(f"{adj[i]:.4e}"),
                     "gene_class": classes[i],
                     "label": f"GENE{i+1:04d}" if sig and rng.random() < 0.3 else ""})
    return pd.DataFrame(rows), None


def b_enrichment(rng):
    terms = [
        ("Interferon gamma response", "Hallmark"), ("Oxidative phosphorylation", "Hallmark"),
        ("Epithelial migration", "GO_BP"), ("Cell cycle checkpoint", "Reactome"),
        ("Antigen processing", "GO_BP"), ("Complement cascade", "Reactome"),
        ("DNA repair", "Hallmark"), ("T cell activation", "GO_BP"),
        ("Apoptosis", "Hallmark"), ("mTOR signaling", "Reactome"),
        ("Extracellular matrix", "GO_CC"), ("Hypoxia", "Hallmark"),
    ]
    rows = []
    for term, cat in terms:
        ratio = float(rng.uniform(0.05, 0.35))
        count = int(rng.integers(20, 70))
        fdr = float(10 ** (-rng.uniform(1.5, 5.0)))
        rows.append({"term": term, "category": cat, "gene_ratio": round(ratio, 3),
                     "gene_count": count, "fdr": float(f"{fdr:.3e}"),
                     "neg_log10_fdr": round(float(-np.log10(fdr)), 3)})
    return pd.DataFrame(rows), None


def b_kaplan_meier(rng):
    # Survival times for low- vs high-risk groups (~30% censored).
    rows = []
    n = 0
    for grp, scale in [("Low_risk", 34.0), ("High_risk", 14.0)]:
        for _ in range(60):
            n += 1
            t = float(rng.exponential(scale))
            t = min(t, 60.0)
            censored = (t >= 60.0) or (rng.random() < 0.25)
            rows.append({"sample_id": f"{'Lo' if grp=='Low_risk' else 'Hi'}_{n:03d}",
                         "group": grp, "time_months": round(t, 2),
                         "event": 0 if censored else 1,
                         "censor_reason": "lost_to_followup" if censored else ""})
    return pd.DataFrame(rows), None


def b_stacked(rng):
    # Cell-type composition fractions per sample (sum to 1), two groups.
    cell_types = ["T_cell", "B_cell", "Myeloid", "Stromal", "Epithelial"]
    rows = []
    for i in range(1, 31):
        grp = "Control" if i <= 15 else "Treated"
        alpha = [3, 2, 2, 1.5, 1.5] if grp == "Control" else [2, 1.5, 3, 1.5, 2]
        fracs = rng.dirichlet(alpha)
        for ct, f in zip(cell_types, fracs):
            rows.append({"sample_id": f"S{i:02d}", "group": grp, "cell_type": ct,
                         "fraction": round(float(f), 4)})
    return pd.DataFrame(rows), None


def b_waterfall(rng):
    # Best % change in tumor size per patient (oncology waterfall).
    rows = []
    for i in range(1, 41):
        val = float(np.clip(rng.normal(-15, 35), -95, 60))
        cat = "PR" if val <= -30 else ("PD" if val >= 20 else "SD")
        rows.append({"patient_id": f"P{i:03d}", "treatment_arm": rng.choice(["Arm_A", "Arm_B"]),
                     "best_percent_change": round(val, 1), "response_category": cat,
                     "duration_months": round(float(rng.uniform(1, 18)), 1)})
    return pd.DataFrame(rows), None


def b_pca(rng):
    # Expression matrix (50 genes x 12 samples) + sample metadata.
    samples = [f"S{i:02d}" for i in range(1, 13)]
    groups = ["Control"] * 6 + ["Treated"] * 6
    batches = [f"Batch_{1 + (i % 2)}" for i in range(12)]
    mat = rng.normal(5.0, 0.8, (50, 12))
    # group separation on first 20 genes; mild batch effect
    for j in range(12):
        if groups[j] == "Treated":
            mat[:20, j] += 1.3
        if batches[j] == "Batch_2":
            mat[:, j] += 0.4
    matrix = pd.DataFrame(mat.round(3), columns=samples)
    matrix.insert(0, "gene", [f"Gene_{i:03d}" for i in range(1, 51)])
    meta = pd.DataFrame({
        "sample_id": samples, "group": groups, "batch": batches,
        "library_size_millions": [round(float(rng.uniform(20, 40)), 2) for _ in samples],
    })
    return matrix, meta


def b_oncoprint(rng):
    genes = ["TP53", "PIK3CA", "KRAS", "EGFR", "PTEN", "MYC", "BRAF", "APC", "ALK", "CDKN2A"]
    patients = [f"P{i:03d}" for i in range(1, 25)]
    alts = ["Missense", "Truncating", "Amplification", "Deletion", "Fusion"]
    rows = []
    for gi, gene in enumerate(genes):
        freq = 0.5 * (1 - gi / len(genes)) + 0.08   # higher genes mutated more often
        for pat in patients:
            if rng.random() < freq:
                a = rng.choice(alts, p=[0.45, 0.2, 0.15, 0.12, 0.08])
                rows.append({"patient_id": pat, "gene": gene, "alteration_type": a,
                             "variant_annotation": "p.X" if a in ("Missense", "Truncating") else a,
                             "variant_allele_fraction": round(float(rng.uniform(0.1, 0.9)), 2)
                             if a in ("Missense", "Truncating") else ""})
    return pd.DataFrame(rows), None


def b_lollipop(rng):
    types = ["Missense", "Nonsense", "Frameshift", "In_frame_del"]
    rows = []
    used = set()
    for _ in range(40):
        pos = int(rng.integers(20, 950))
        if pos in used:
            continue
        used.add(pos)
        mt = rng.choice(types, p=[0.6, 0.15, 0.15, 0.1])
        domain = "Kinase" if 300 <= pos <= 600 else ("SH2" if 700 <= pos <= 820 else "Other")
        rows.append({"gene": "GENE_X", "protein_position": pos,
                     "amino_acid_change": f"p.{rng.choice(list('ACDEFGHIKLMNPQRSTVWY'))}{pos}"
                                          f"{rng.choice(list('ACDEFGHIKLMNPQRSTVWY*'))}",
                     "mutation_type": mt, "sample_count": int(rng.integers(1, 12)),
                     "domain": domain})
    return pd.DataFrame(rows).sort_values("protein_position").reset_index(drop=True), None


def b_roc(rng):
    # Binary labels + scores from a strong model A and weaker model B.
    rows = []
    for i in range(1, 121):
        label = 0 if i <= 60 else 1
        cohort = "Discovery" if i % 2 == 0 else "Validation"
        a = float(np.clip(rng.normal(0.7 if label else 0.35, 0.13), 0, 1))
        b = float(np.clip(rng.normal(0.6 if label else 0.45, 0.18), 0, 1))
        rows.append({"sample_id": f"S{i:03d}", "true_label": label,
                     "score_model_a": round(a, 4), "score_model_b": round(b, 4),
                     "cohort": cohort})
    return pd.DataFrame(rows), None


def b_forest(rng):
    subgroups = ["All patients", "Age < 65", "Age >= 65", "Male", "Female",
                 "Biomarker high", "Biomarker low", "Prior therapy yes", "Prior therapy no"]
    rows = []
    for i, sg in enumerate(subgroups):
        hr = float(np.clip(rng.normal(1.0, 0.35), 0.3, 2.2))
        se = float(rng.uniform(0.12, 0.3))
        rows.append({"study": f"Study_{i+1}", "subgroup": sg,
                     "hazard_ratio": round(hr, 3),
                     "ci_low": round(hr * np.exp(-1.96 * se), 3),
                     "ci_high": round(hr * np.exp(1.96 * se), 3),
                     "p_value": round(float(rng.uniform(0.005, 0.4)), 4),
                     "n": int(rng.integers(80, 400))})
    return pd.DataFrame(rows), None


def b_ridge(rng):
    # Single-cell-like score distribution along pseudotime per condition.
    rows = []
    n = 0
    for cond, loc in [("Control", 0.35), ("Stimulated", 0.6), ("Inhibited", 0.25)]:
        for _ in range(350):
            n += 1
            pt = float(np.clip(rng.normal(loc, 0.18), 0, 1))
            rows.append({"cell_id": f"C{n:04d}",
                         "sample_id": f"{cond[:3]}_S{rng.integers(1,4)}",
                         "condition": cond, "pseudotime": round(pt, 4),
                         "score": round(float(rng.normal(3 + 2 * pt, 0.7)), 3)})
    return pd.DataFrame(rows), None


# ---------------------------------------------------------------------------
# v0.4 builders (manuscript plot-type expansion). Synthetic, deterministic.
# ---------------------------------------------------------------------------
def b_dot_strip(rng):
    # Individual observations per group — a readable alternative to a bar plot.
    rows = []
    for g, m in [("Healthy", 4.6), ("Disease", 6.1), ("Treated", 5.3)]:
        for _ in range(26):
            rows.append({"group": g, "value": round(float(rng.normal(m, 0.7)), 3),
                         "cohort": rng.choice(["Discovery", "Validation"])})
    return pd.DataFrame(rows), None


def b_beeswarm(rng):
    # Assay readout per dose group; each point is one well/replicate.
    rows = []
    for g, m in [("Vehicle", 4.2), ("Low_dose", 5.1), ("High_dose", 6.4)]:
        for _ in range(28):
            rows.append({"group": g, "value": round(float(rng.normal(m, 0.8)), 3),
                         "sex": rng.choice(["M", "F"])})
    return pd.DataFrame(rows), None


def b_paired_slope(rng):
    # Matched before/after: one subject measured at two timepoints.
    rows = []
    for s in range(22):
        base = rng.normal(12, 2.5)
        arm = rng.choice(["Placebo", "Active"])
        eff = {"Placebo": 1.0, "Active": 4.0}[arm]
        for cond, d in [("Baseline", 0.0), ("Week_12", eff)]:
            rows.append({"subject": f"P{s + 1:02d}", "condition": cond,
                         "value": round(float(base + d + rng.normal(0, 1)), 3),
                         "arm": arm})
    return pd.DataFrame(rows), None


def b_raincloud(rng):
    # Distribution per group: cloud (density) + box + raw points.
    rows = []
    for g, m, sd in [("Healthy", 4.6, 0.5), ("Disease", 6.1, 0.9), ("Treated", 5.3, 0.7)]:
        for i in range(35):
            rows.append({"group": g, "value": round(float(rng.normal(m, sd)), 3),
                         "batch": f"B{1 + i % 3}"})
    return pd.DataFrame(rows), None


def b_dendrogram(rng):
    # Expression matrix: 24 genes x 10 samples with clear two-block structure.
    n_genes = 24
    samples = [f"{grp}_{i}" for grp in ("Tumor", "Normal") for i in range(1, 6)]
    base = rng.normal(0, 1, (n_genes, len(samples)))
    base[:12, :5] += 2.0
    base[12:, 5:] += 2.0
    data = {"gene": [f"Gene_{i:02d}" for i in range(1, n_genes + 1)]}
    for j, s in enumerate(samples):
        data[s] = np.round(base[:, j], 3)
    return pd.DataFrame(data), None


def b_ma(rng):
    # Differential-expression table: mean expression vs log2 fold change.
    n = 600
    ave = rng.uniform(1, 14, n)
    lfc = rng.normal(0, 0.8, n)
    up = rng.choice(n, 35, replace=False)
    lfc[up] += rng.uniform(2, 5, 35)
    dn = rng.choice([i for i in range(n) if i not in up], 35, replace=False)
    lfc[dn] -= rng.uniform(2, 5, 35)
    p = rng.uniform(0.2, 1, n)
    p[up] = rng.uniform(1e-6, 0.02, 35)
    p[dn] = rng.uniform(1e-6, 0.02, 35)
    return pd.DataFrame({"AveExpr": np.round(ave, 3), "logFC": np.round(lfc, 3),
                         "adj.P.Val": p, "gene": [f"GENE{i:04d}" for i in range(n)]}), None


def b_manhattan(rng):
    # GWAS summary statistics across chromosomes 1-22 + X, with a few real hits.
    rows = []
    for c in [str(i) for i in range(1, 23)] + ["X"]:
        for _ in range(int(rng.integers(40, 90))):
            rows.append({"chromosome": c, "position": int(rng.integers(1, 2_000_000)),
                         "p_value": float(rng.uniform(1e-3, 1)),
                         "snp": f"rs{rng.integers(1, 9_999_999)}"})
    for _ in range(6):
        rows.append({"chromosome": str(rng.integers(1, 23)),
                     "position": int(rng.integers(1, 2_000_000)),
                     "p_value": float(rng.uniform(1e-12, 4e-8)),
                     "snp": f"rs{rng.integers(1, 9_999_999)}"})
    return pd.DataFrame(rows), None


def b_qq(rng):
    # GWAS p-values: mostly null (uniform) with a handful of true associations.
    n = 1200
    p = rng.uniform(0, 1, n)
    hits = rng.choice(n, 25, replace=False)
    p[hits] = rng.uniform(1e-10, 1e-4, 25)
    return pd.DataFrame({"p_value": np.clip(p, 1e-12, 1)}), None


def b_precision_recall(rng):
    # Two classifiers on an imbalanced binary outcome (35% positive).
    def sigmoid(z):
        return 1.0 / (1.0 + np.exp(-z))
    n = 180
    y = rng.binomial(1, 0.35, n)
    a = sigmoid(1.8 * y + rng.normal(0, 1.0, n))      # stronger model
    b = sigmoid(1.0 * y + rng.normal(0, 1.3, n))      # weaker model
    return pd.DataFrame({
        "sample_id": [f"S{i:03d}" for i in range(n)],
        "true_label": y,
        "score_model_a": np.round(a, 4),
        "score_model_b": np.round(b, 4),
        "cohort": rng.choice(["Discovery", "Validation"], n),
    }), None


def b_confusion(rng):
    # 3-class diagnostic classifier with a believable, diagonal-heavy confusion.
    classes = ["Normal", "Benign", "Malignant"]
    conf = {"Normal": [0.85, 0.10, 0.05], "Benign": [0.12, 0.78, 0.10],
            "Malignant": [0.04, 0.16, 0.80]}
    rows = []
    for i in range(240):
        t = rng.choice(classes)
        p = rng.choice(classes, p=conf[t])
        rows.append({"sample_id": f"S{i:03d}", "true_label": t, "predicted_label": p})
    return pd.DataFrame(rows), None


def b_calibration(rng):
    # A slightly over-confident risk model: labels drawn from a true risk,
    # predictions are a mildly miscalibrated transform of it.
    def sigmoid(z):
        return 1.0 / (1.0 + np.exp(-z))
    n = 400
    p_true = rng.beta(2, 3, n)
    y = rng.binomial(1, p_true)
    logit = np.log(p_true / (1 - p_true))
    pred = np.clip(sigmoid(1.15 * logit + 0.1), 0.001, 0.999)
    return pd.DataFrame({
        "sample_id": [f"S{i:03d}" for i in range(n)],
        "true_label": y,
        "predicted_prob": np.round(pred, 4),
    }), None


def b_dose_response(rng):
    # Two drugs with sigmoidal viability response across concentration decades.
    rows = []
    for drug, ec50, hill in [("DrugA", 0.4, 1.2), ("DrugB", 6.0, 1.4)]:
        for c in np.logspace(-2.5, 2.5, 10):
            for _ in range(3):
                resp = 100.0 / (1.0 + (c / ec50) ** hill) + rng.normal(0, 4)
                rows.append({"drug": drug, "concentration_uM": round(float(c), 4),
                             "viability_pct": round(float(resp), 2)})
    return pd.DataFrame(rows), None


def b_swimmer(rng):
    # Per-patient oncology timelines with response category + an event marker.
    resp = ["CR", "PR", "SD", "PD"]
    events = ["response", "progression", "death", "ongoing"]
    rows = []
    for i in range(20):
        dur = float(rng.uniform(2, 26))
        rows.append({"patient_id": f"P{i + 1:02d}", "start_month": 0.0,
                     "end_month": round(dur, 1), "duration_month": round(dur, 1),
                     "response": rng.choice(resp), "event_type": rng.choice(events)})
    return pd.DataFrame(rows), None


def b_spider(rng):
    # Longitudinal per-patient % change (tumor burden) by response arm.
    arms = ["Responder", "Non-responder"]
    rows = []
    for i in range(14):
        arm = rng.choice(arms)
        base = 0.0
        for wk in [0, 4, 8, 12, 16, 20]:
            base += rng.normal(-7 if arm == "Responder" else 6, 4)
            rows.append({"patient_id": f"S{i + 1:02d}", "week": wk,
                         "pct_change": round(base, 1), "arm": arm})
    return pd.DataFrame(rows), None


def b_embedding(rng):
    # Precomputed 2D embedding: Gaussian blobs per cell type (scRNA-seq-like).
    centers = {"T_cell": (0, 0), "B_cell": (6.5, 1), "Myeloid": (3, 6.5),
               "NK": (-4.5, 4.5), "Dendritic": (7, 7)}
    rows = []
    for cl, (cx, cy) in centers.items():
        for _ in range(70):
            rows.append({"UMAP_1": round(float(rng.normal(cx, 0.9)), 3),
                         "UMAP_2": round(float(rng.normal(cy, 0.9)), 3),
                         "cell_type": cl, "batch": f"batch_{rng.integers(1, 3)}",
                         "n_genes": int(rng.integers(800, 4000))})
    return pd.DataFrame(rows), None


def b_upset(rng):
    # Binary set membership: each gene is in/out of several feature sets.
    n = 280
    probs = {"DEG_up": 0.42, "DEG_down": 0.31, "Promoter_peak": 0.5, "Conserved": 0.36}
    data = {"gene": [f"GENE{i:04d}" for i in range(n)]}
    for s, p in probs.items():
        data[s] = (rng.random(n) < p).astype(int)
    return pd.DataFrame(data), None


def b_sankey(rng):
    # Flow from baseline response category to clinical outcome.
    srcs = {"Responder": 60, "Stable": 90, "Progressor": 50}
    tgts = ["Alive", "Deceased", "Lost to follow-up"]
    rows = []
    for s, tot in srcs.items():
        w = rng.dirichlet(np.ones(3)) * tot
        for t, v in zip(tgts, w):
            rows.append({"baseline_response": s, "outcome": t, "n_patients": int(round(v)) + 1})
    return pd.DataFrame(rows), None


def b_bland_altman(rng):
    # Two devices measuring the same quantity; device_A has a small positive bias.
    n = 90
    true = rng.normal(52, 11, n)
    rows = [{"sample_id": f"S{i:03d}",
             "device_A": round(float(true[i] + rng.normal(1.2, 3.0)), 2),
             "device_B": round(float(true[i] + rng.normal(0, 3.0)), 2)} for i in range(n)]
    return pd.DataFrame(rows), None


# ---------------------------------------------------------------------------
# v0.5 builders (networks + hierarchical clustering).
# ---------------------------------------------------------------------------
def b_network(rng):
    # Synthetic gene-interaction network: 18 genes in 3 functional modules,
    # edges preferentially within-module (STRING-like confidence weights).
    modules = {"Immune": 6, "Metabolic": 6, "Signaling": 6}
    genes, gene_group, gi = [], {}, 0
    for mod, k in modules.items():
        for _ in range(k):
            g = f"GENE{gi:02d}"
            genes.append(g)
            gene_group[g] = mod
            gi += 1
    rows, seen = [], set()
    for g in genes:
        same = [h for h in genes if gene_group[h] == gene_group[g] and h != g]
        for h in rng.choice(same, size=min(3, len(same)), replace=False):
            key = tuple(sorted((g, h)))
            if key in seen:
                continue
            seen.add(key)
            rows.append({"source": key[0], "target": key[1],
                         "weight": round(float(rng.uniform(0.55, 0.99)), 2),
                         "interaction_type": rng.choice(["activation", "binding"])})
    for _ in range(6):
        a, b = rng.choice(genes, 2, replace=False)
        key = tuple(sorted((a, b)))
        if key in seen:
            continue
        seen.add(key)
        rows.append({"source": key[0], "target": key[1],
                     "weight": round(float(rng.uniform(0.30, 0.55)), 2),
                     "interaction_type": "regulation"})
    edges = pd.DataFrame(rows)
    nodes = pd.DataFrame({"node": genes,
                          "group": [gene_group[g] for g in genes],
                          "value": np.round(rng.uniform(-2, 2, len(genes)), 2)})
    return edges, nodes


def write_network_extra_files(folder, edges, nodes, rng):
    """Write the alternate network input formats next to data.csv/nodes.csv."""
    edges.to_csv(os.path.join(folder, "edge_list.csv"), index=False)
    nodes.to_csv(os.path.join(folder, "node_attributes.csv"), index=False)
    gs = list(nodes["node"])
    crows = []
    for i in range(len(gs)):
        for j in range(i + 1, len(gs)):
            if rng.random() < 0.28:
                crows.append({"source": gs[i], "target": gs[j],
                              "correlation": round(float(rng.uniform(-0.95, 0.95)), 2)})
    pd.DataFrame(crows).to_csv(os.path.join(folder, "correlation_network.csv"), index=False)
    n = len(gs)
    idx = {g: k for k, g in enumerate(gs)}
    M = np.zeros((n, n))
    for _, r in edges.iterrows():
        a, b = idx[r["source"]], idx[r["target"]]
        M[a, b] = M[b, a] = r["weight"]
    adj = pd.DataFrame(M, columns=gs)
    adj.insert(0, "node", gs)
    adj.to_csv(os.path.join(folder, "adjacency_matrix.csv"), index=False)


def b_hier_clustering(rng):
    # Expression matrix: 30 genes x 12 samples with 3 clear gene modules.
    samples = [f"{grp}_{i}" for grp in ("Ctrl", "TreatA", "TreatB") for i in range(1, 5)]
    base = rng.normal(0, 0.6, (30, len(samples)))
    base[:10, 0:4] += 2.2
    base[10:20, 4:8] += 2.2
    base[20:, 8:12] += 2.2
    data = {"gene": [f"Gene_{i:02d}" for i in range(1, 31)]}
    for j, s in enumerate(samples):
        data[s] = np.round(base[:, j], 3)
    return pd.DataFrame(data), None


@dataclass
class Example:
    plot_type: str
    slug: str
    sheet: str          # Excel-safe (<=31 chars), unique
    use_case: str
    builder: Callable
    required_columns: List[str]
    optional_columns: List[str] = field(default_factory=list)
    replace_help: str = ""
    common_mistakes: List[str] = field(default_factory=list)
    aux_name: Optional[str] = None    # e.g. "metadata" for PCA


EXAMPLES: List[Example] = [
    Example("barplot_with_error_bar", "bar_error", "Bar_error",
            "Compare a mean readout across experimental conditions with replicate error bars.",
            b_bar_error, ["condition", "replicate", "measurement"], ["unit", "experiment_batch"],
            "Keep one row per replicate. Replace the condition labels and measurement values; "
            "the app computes the mean and SEM/SD/CI for you.",
            ["Do not pre-average — give raw replicate rows.",
             "Keep 'condition' as text, 'measurement' as numbers."]),
    Example("grouped_barplot_with_error_bar", "grouped_bar", "Grouped_bar",
            "Two-factor comparison (e.g. genotype x treatment) with grouped bars and error bars.",
            b_grouped_bar, ["genotype", "treatment", "replicate", "expression"], ["gene", "unit"],
            "One row per replicate. 'genotype' is the x-axis, 'treatment' is the grouping color.",
            ["Keep both grouping columns categorical (text)."]),
    Example("boxplot_or_violin_with_points", "box_violin", "Box_violin",
            "Show full distributions per group as box or violin plots with overlaid points.",
            b_box_violin, ["sample_id", "group", "value"], ["batch", "sex"],
            "One row per sample/observation. Switch box vs violin with the 'kind' option.",
            ["Use enough samples per group (>=5) for a meaningful distribution."]),
    Example("scatterplot_with_regression", "scatter", "Scatter",
            "Relationship between two continuous variables, colored by group, optional fit line.",
            b_scatter, ["sample_id", "x_marker", "y_response"], ["group", "label"],
            "x and y must be numeric. Leave 'label' blank for points you don't want annotated.",
            ["Blank labels are fine; non-numeric x/y will be dropped."]),
    Example("lineplot_timecourse_with_error_band", "line_timecourse", "Line_timecourse",
            "Mean response over time per treatment, with a shaded SEM/CI error band.",
            b_line_timecourse, ["time_hours", "treatment", "replicate", "signal"], ["unit"],
            "Long format: one row per time point per replicate. 'treatment' colors the lines.",
            ["Keep time numeric and data in long (not wide) format."]),
    Example("heatmap_clustered_matrix", "heatmap", "Heatmap",
            "Gene-by-sample expression matrix with optional row/column clustering.",
            b_heatmap, ["gene", "<sample columns>"], [],
            "First column = row label (gene). All other columns are numeric samples.",
            ["Keep the first column as labels; every other column must be numeric."]),
    Example("volcano_plot", "volcano", "Volcano",
            "Differential expression: log2 fold change vs significance, highlighting hits.",
            b_volcano, ["gene", "log2_fold_change", "p_value"],
            ["adjusted_p_value", "gene_class", "label"],
            "One row per gene/feature. Provide p_value (and adjusted_p_value if available).",
            ["p-values must be numeric (scientific notation is fine)."]),
    Example("enrichment_dotplot", "enrichment", "Enrichment_dot",
            "Pathway/term enrichment: dot size = gene count, color = significance.",
            b_enrichment, ["term", "gene_ratio", "fdr"], ["category", "gene_count", "neg_log10_fdr"],
            "One row per enriched term. Provide FDR (the app derives -log10 FDR if missing).",
            ["gene_ratio should be a fraction between 0 and 1."]),
    Example("kaplan_meier_survival_curve", "kaplan_meier", "Kaplan_Meier",
            "Survival probability over time by group, with censoring marks.",
            b_kaplan_meier, ["sample_id", "group", "time_months", "event"], ["censor_reason"],
            "One row per patient. event=1 means the event occurred; event=0 means censored.",
            ["Encode event as 1/0, not text."]),
    Example("stacked_bar_composition", "stacked", "Stacked_composition",
            "Cell-type (or category) composition per sample as stacked fractions.",
            b_stacked, ["sample_id", "cell_type", "fraction"], ["group"],
            "Long format: one row per sample per cell type. Fractions should sum to ~1 per sample.",
            ["Fractions per sample should add up to about 1.0."]),
    Example("waterfall_plot", "waterfall", "Waterfall",
            "Best percent change per patient (oncology response), sorted into a waterfall.",
            b_waterfall, ["patient_id", "best_percent_change"],
            ["treatment_arm", "response_category", "duration_months"],
            "One row per patient. Use negative values for tumor shrinkage.",
            ["best_percent_change must be numeric (can be negative)."]),
    Example("pca_scatter_from_matrix", "pca", "PCA",
            "PCA of an expression matrix; samples colored by group and shaped by batch.",
            b_pca, ["gene", "<sample columns>"], [],
            "Provide the matrix (genes x samples) as data, and a metadata table whose "
            "'sample_id' matches the matrix sample column names.",
            ["Metadata sample_id values must exactly match the matrix column headers."],
            aux_name="metadata"),
    Example("oncoprint_mutation_heatmap", "oncoprint", "Oncoprint",
            "Gene-by-sample alteration grid (oncoprint) colored by alteration type.",
            b_oncoprint, ["patient_id", "gene", "alteration_type"],
            ["variant_annotation", "variant_allele_fraction"],
            "One row per alteration (a patient/gene can appear multiple times).",
            ["alteration_type should use a small, consistent set of labels."]),
    Example("lollipop_mutation_plot", "lollipop", "Lollipop",
            "Mutation counts along a protein, as lollipops colored by mutation type.",
            b_lollipop, ["gene", "protein_position", "sample_count"],
            ["amino_acid_change", "mutation_type", "domain"],
            "One row per protein position. Positions and counts must be integers.",
            ["Use integer protein positions and counts."]),
    Example("roc_curve", "roc", "ROC",
            "ROC curves with AUC comparing one or two classifier scores.",
            b_roc, ["sample_id", "true_label", "score_model_a"], ["score_model_b", "cohort"],
            "true_label is 1 for the positive class, 0 for negative. Scores are continuous.",
            ["Include both classes (some 1s and some 0s)."]),
    Example("forest_plot", "forest", "Forest",
            "Subgroup effect sizes (hazard/odds ratios) with confidence intervals.",
            b_forest, ["subgroup", "hazard_ratio", "ci_low", "ci_high"], ["study", "p_value", "n"],
            "One row per subgroup. Provide the estimate and its CI bounds.",
            ["ci_low must be <= estimate <= ci_high."]),
    Example("ridge_or_density_plot", "ridge", "Ridgeline",
            "Stacked density (ridgeline) distributions of a value per condition.",
            b_ridge, ["cell_id", "condition", "pseudotime"], ["sample_id", "score"],
            "One row per observation. The x value (pseudotime/score) must be numeric.",
            ["Provide many rows per group for smooth densities."]),
    # --- v0.4 manuscript plot types ---
    Example("dot_strip_plot", "dot_strip", "Dot_strip",
            "Show every observation per group with an optional mean/median summary — a readable "
            "alternative to a bar plot.",
            b_dot_strip, ["group", "value"], ["cohort"],
            "One row per observation. 'group' is categorical (x); 'value' is numeric (y). "
            "Choose the summary overlay (mean/median with SD/SEM/CI) or turn it off.",
            ["Give raw observations, not group means.",
             "Keep 'group' as text and 'value' as numbers."]),
    Example("beeswarm_plot", "beeswarm", "Beeswarm",
            "Show every observation per group with a collision-avoiding layout — a readable "
            "alternative to a bar plot.",
            b_beeswarm, ["group", "value"], ["sex"],
            "One row per observation. 'group' is categorical (x); 'value' is numeric (y). "
            "Optionally color points by another category.",
            ["Give raw observations, not group means.",
             "Keep 'group' as text and 'value' as numbers."]),
    Example("paired_slopegraph", "paired_slope", "Paired_slope",
            "Connect matched observations across conditions/timepoints (before/after, repeated measures).",
            b_paired_slope, ["subject", "condition", "value"], ["arm"],
            "Long format: one row per subject per condition. 'subject' matches paired rows; "
            "'condition' is the timepoint (x); 'value' is numeric. Optionally color by group.",
            ["Use the same 'subject' id across conditions so lines connect.",
             "Keep data long (one row per subject per condition), not wide."]),
    Example("raincloud_plot", "raincloud", "Raincloud",
            "Full distribution per group as a half-violin cloud + box summary + raw points.",
            b_raincloud, ["group", "value"], ["batch"],
            "One row per observation. 'group' is categorical (x); 'value' is numeric (y).",
            ["Provide enough observations per group (>=10) for a meaningful density.",
             "Keep 'value' numeric."]),
    Example("hierarchical_dendrogram", "dendrogram", "Dendrogram",
            "Hierarchical clustering of a feature-by-sample matrix as a standalone dendrogram.",
            b_dendrogram, ["gene", "<sample columns>"], [],
            "First column = row label (gene). All other columns are numeric samples. "
            "Choose linkage (average/complete/single/ward) and whether to cluster rows or columns.",
            ["Keep the first column as labels; every other column must be numeric.",
             "Ward linkage always uses a Euclidean metric."]),
    Example("ma_plot", "ma_plot", "MA_plot",
            "Differential expression: average abundance (A) vs log fold change (M), colored by significance.",
            b_ma, ["AveExpr", "logFC", "adj.P.Val"], ["gene"],
            "One row per gene/feature. Provide average expression (AveExpr/baseMean/logCPM), "
            "log fold change (logFC/log2FoldChange), and a p-value/FDR column (read verbatim).",
            ["p-values must be numeric; they are never recomputed.",
             "Column names are auto-detected but can be remapped."]),
    Example("manhattan_plot", "manhattan", "Manhattan",
            "Genome-wide association -log10(p) across chromosomes with significance thresholds.",
            b_manhattan, ["chromosome", "position", "p_value"], ["snp"],
            "One row per variant. Provide chromosome, genomic position (numeric), and p-value (numeric).",
            ["Positions must be numeric; p-values in (0, 1].",
             "Chromosomes may be '1'..'22','X','Y','MT' (with or without a 'chr' prefix)."]),
    Example("qq_plot", "qq", "QQ_plot",
            "Observed vs expected -log10(p) Q-Q plot with genomic inflation (lambda).",
            b_qq, ["p_value"], [],
            "For 'pvalue' mode, provide a p-value column. For 'quantile' mode, map 'observed' "
            "to a numeric column to check normality against theoretical quantiles.",
            ["p-values must be numeric and in (0, 1]."]),
    Example("bland_altman_plot", "bland_altman", "Bland_Altman",
            "Agreement between two measurement methods (bias and limits of agreement).",
            b_bland_altman, ["device_A", "device_B"], ["sample_id"],
            "One row per paired measurement. Map the two method/device columns; both must be numeric.",
            ["Both method columns must be numeric.",
             "Rows are paired measurements of the SAME samples."]),
    Example("precision_recall_curve", "precision_recall", "Precision_recall",
            "Precision vs recall for one or two classifiers on an imbalanced outcome, with average precision (AUPRC).",
            b_precision_recall, ["true_label", "score_model_a"], ["score_model_b", "cohort"],
            "true_label is 1 for the positive class, 0 for negative. Scores are continuous model outputs.",
            ["Include both classes (some 1s and some 0s).",
             "AUPRC is the average precision; it is computed only from valid labels+scores."]),
    Example("confusion_matrix", "confusion_matrix", "Confusion",
            "Classification confusion matrix (binary or multiclass) with optional row/column/total normalization.",
            b_confusion, ["true_label", "predicted_label"], [],
            "One row per prediction: the true class and the predicted class. Or provide a "
            "precomputed matrix (first column = true label, other columns = predicted classes).",
            ["Use a small, consistent set of class labels.",
             "Switch counts vs percentages with the 'normalize' option."]),
    Example("calibration_plot", "calibration", "Calibration",
            "Reliability of a clinical risk model: predicted vs observed probability, binned, with a "
            "perfect-calibration diagonal.",
            b_calibration, ["true_label", "predicted_prob"], [],
            "true_label is 1/0; predicted_prob is the model's probability in [0,1]. Or provide "
            "precomputed 'predicted' and 'observed' probability columns.",
            ["Predicted probabilities must be between 0 and 1.",
             "The Brier score is reported in metadata, not drawn on the figure."]),
    Example("dose_response_curve", "dose_response", "Dose_response",
            "Drug dose-response with a 4-parameter logistic fit and EC50/IC50 per group.",
            b_dose_response, ["concentration_uM", "viability_pct"], ["drug"],
            "One row per well/measurement. Dose must be positive (log x-axis). Optionally group by "
            "drug/condition. A 4PL curve is fit per group when 'fit' is on; EC50 is reported only "
            "when the fit converges.",
            ["Dose must be positive (non-positive doses are dropped for the log axis).",
             "Provide several dose levels spanning the response so the fit can converge."]),
    Example("upset_plot", "upset", "UpSet",
            "Intersections among many sets (a scalable alternative to Venn diagrams).",
            b_upset, ["DEG_up", "DEG_down", "Promoter_peak", "Conserved"], ["gene"],
            "Use one 0/1 column per set (each row = one element), or long form (element + set columns). "
            "Set mapping['sets'] to your set columns.",
            ["Membership columns must be 0/1 (or boolean).",
             "Provide at least 2 sets."]),
    Example("swimmer_plot", "swimmer", "Swimmer",
            "Per-patient treatment/follow-up timelines (oncology), colored by response with event markers.",
            b_swimmer, ["patient_id", "end_month"],
            ["start_month", "duration_month", "event_type", "response"],
            "One row per patient. Provide an 'end' time (or a 'duration'); 'start' defaults to 0. "
            "Optionally add an event-type column (progression/death/response/...) and a group column.",
            ["Give an end time OR a duration.",
             "Keep event/response labels to a small consistent set."]),
    Example("spider_plot", "spider", "Spider",
            "Longitudinal per-patient change over time (e.g. % change in tumor burden), one line per patient.",
            b_spider, ["patient_id", "week", "pct_change"], ["arm"],
            "Long format: one row per patient per timepoint. 'time' and 'value' must be numeric. "
            "Optionally color by a response/treatment group; set a reference line (default 0%).",
            ["Keep the data long (one row per patient per timepoint), not wide.",
             "time and value must be numeric."]),
    Example("sankey_plot", "sankey", "Sankey",
            "Flow between two sets of categories (e.g. baseline state -> outcome).",
            b_sankey, ["baseline_response", "outcome", "n_patients"], [],
            "One row per source->target flow, with a numeric 'value'. Map your source, target, "
            "and value columns.",
            ["'value' must be numeric and positive.",
             "v0.4 supports two-stage flows (source -> target) only."]),
    Example("embedding_scatter", "embedding", "Embedding",
            "Single-cell / sample embedding (UMAP or t-SNE) colored by cluster or metadata.",
            b_embedding, ["UMAP_1", "UMAP_2"], ["cell_type", "batch", "n_genes"],
            "Upload PRECOMPUTED coordinates (one row per cell/sample). Point color can be a "
            "category (cluster/cell type) or a continuous value; the app picks a legend or colorbar. "
            "Upload precomputed UMAP/t-SNE coordinates as a table; direct .h5ad/AnnData "
            "support is planned for a future version.",
            ["Compute UMAP/t-SNE in your analysis tool first — this plots existing coordinates.",
             "Coordinate columns must be numeric (e.g. UMAP_1, UMAP_2)."]),
    # --- v0.5 ---
    Example("network_graph", "network", "Network",
            "Interaction / co-expression network: nodes are genes/features, edges are "
            "interactions or correlations, colored by module and sized by degree.",
            b_network, ["source", "target"], ["weight", "interaction_type"],
            "Provide an edge list (source, target, optional weight). Add a node-attributes table "
            "(nodes.csv) with node, group, value to color/size nodes. Adjacency-matrix and "
            "correlation-network modes are also supported (see the folder).",
            ["Keep source/target as node names (text).",
             "A correlation network shows association, not a mechanistic interaction."],
            aux_name="nodes"),
    Example("hierarchical_clustering", "hier_clustering", "Hier_clustering",
            "Cluster a feature-by-sample matrix into k groups and export the cluster assignment table.",
            b_hier_clustering, ["gene", "<sample columns>"], [],
            "First column = row label (gene); other columns are numeric samples. Choose k, scaling, "
            "distance metric, and linkage; the cluster assignment is exported as a table.",
            ["Keep the first column as labels; every other column must be numeric.",
             "Ward linkage requires the euclidean metric.",
             "k must be between 2 and the number of clustered objects."]),
]


def _write_table(df: pd.DataFrame, base: str):
    df.to_csv(base + ".csv", index=False)
    df.to_csv(base + ".tsv", sep="\t", index=False)
    with pd.ExcelWriter(base + ".xlsx", engine="openpyxl") as xw:
        df.to_excel(xw, index=False, sheet_name="data")


def _readme(ex: Example, manifest_entry: Dict[str, Any]) -> str:
    req = "\n".join(f"  - `{c}`" for c in ex.required_columns)
    opt = "\n".join(f"  - `{c}`" for c in ex.optional_columns) or "  - (none)"
    mistakes = "\n".join(f"  - {m}" for m in ex.common_mistakes) or "  - (none)"
    aux = ""
    if ex.aux_name == "metadata":
        aux = ("\n## Auxiliary table\n\n"
               "This plot also needs `metadata.csv` (sample metadata). Its `sample_id` "
               "values must match the sample column names in `data.*`.\n")
    elif ex.aux_name == "nodes":
        aux = ("\n## Auxiliary table\n\n"
               "This plot can use `nodes.csv` (node attributes): a `node` column plus optional "
               "`group`/`value` to color and size nodes. This folder also includes alternate "
               "inputs: `edge_list.csv`, `node_attributes.csv`, `correlation_network.csv`, and "
               "`adjacency_matrix.csv`.\n")
    elif ex.aux_name:
        aux = (f"\n## Auxiliary table\n\nThis plot also uses `{ex.aux_name}.csv`.\n")
    return f"""# {display_name(ex.plot_type)} — example data

**Plot type id:** `{ex.plot_type}`

**Scientific use case:** {ex.use_case}

> ⚠️ **Synthetic data.** This dataset was generated by
> `scripts/generate_example_data.py` (seed {SEED}). It is plausible but NOT real
> and must not be cited as a biological finding. License: {LICENSE}.

## What a row represents

One row = one {('replicate/observation' if 'replicate' in ex.required_columns or 'sample_id' in ex.required_columns else 'record')} for this analysis.

## Columns

- **Required:**
{req}
- **Optional:**
{opt}
{aux}
## Files

- `data.csv`, `data.tsv`, `data.xlsx` — the same table in three formats.
- `plotspec.json` — a ready-to-use PlotSpec (plot type, column mapping, style, output).
- Open any of these in the app via **Use example data → {display_name(ex.plot_type)}**.

## Replace with your own data

{ex.replace_help}

Keep the **required column names** above (or remap columns in the app). Column
order does not matter — the app validates by name and type.

## Common mistakes to avoid

{mistakes}
"""


def main() -> int:
    os.makedirs(BY_PLOT_DIR, exist_ok=True)
    manifest: Dict[str, Any] = {
        "project": "make_my_figure",
        "generated_by": SOURCE,
        "seed": SEED,
        "data_type": "synthetic",
        "license": LICENSE,
        "note": ("All example datasets are synthetic. Published papers/figures are used only "
                 "as visual style references (layout, typography, panels, legends), never as a "
                 "source of copied data. Do not cite these examples as real findings."),
        "combined_workbook": os.path.relpath(COMBINED_XLSX, _ROOT),
        "plot_types": [],
    }
    combined_sheets: List[Tuple[str, pd.DataFrame]] = []

    rng_master = np.random.default_rng(SEED)
    for i, ex in enumerate(EXAMPLES):
        rng = np.random.default_rng(SEED + i)  # per-plot reproducible stream
        df, aux = ex.builder(rng)
        folder = os.path.join(BY_PLOT_DIR, ex.slug)
        os.makedirs(folder, exist_ok=True)
        base = os.path.join(folder, "data")
        _write_table(df, base)
        if aux is not None and ex.aux_name:
            _write_table(aux, os.path.join(folder, ex.aux_name))
        if ex.plot_type == "network_graph" and aux is not None:
            # Also write the alternate network input formats for the docs/QA.
            write_network_extra_files(folder, df, aux, np.random.default_rng(SEED + 777))

        # PlotSpec JSON
        mapping = default_mapping(ex.plot_type)
        spec: Dict[str, Any] = {
            "plot_type": ex.plot_type,
            "input_table": "data.csv",
            "mapping": mapping,
            "journal_style": "nature_like",
            "output": {"formats": ["svg", "png", "pdf"], "width_mm": 89, "height_mm": 70, "dpi": 300},
            "layout": {"column_width": "single"},
        }
        if ex.aux_name:
            spec["aux_tables"] = {ex.aux_name: f"{ex.aux_name}.csv"}
        with open(os.path.join(folder, "plotspec.json"), "w", encoding="utf-8") as fh:
            json.dump(spec, fh, indent=2)

        rel = os.path.relpath(folder, _ROOT)
        entry = {
            "plot_type": ex.plot_type,
            "name": display_name(ex.plot_type),
            "slug": ex.slug,
            "description": ex.use_case,
            "use_case": ex.use_case,
            "required_columns": ex.required_columns,
            "optional_columns": ex.optional_columns,
            "files": {
                "csv": f"{rel}/data.csv", "tsv": f"{rel}/data.tsv",
                "xlsx": f"{rel}/data.xlsx", "plotspec": f"{rel}/plotspec.json",
                "readme": f"{rel}/README.md",
            },
            "aux_tables": ({ex.aux_name: f"{rel}/{ex.aux_name}.csv"} if ex.aux_name else {}),
            "excel_sheet": ex.sheet,
            "recommended_style_profiles": STYLES,
            "compatible_renderers": [ex.plot_type],
            "expected_export_formats": ["svg", "png", "pdf", "plot_spec.json"],
            "data_type": "synthetic",
            "source": SOURCE,
            "license": LICENSE,
            "provenance": "Synthetic; not derived from any published dataset.",
            "n_rows": int(len(df)),
            "user_replacement_note": ex.replace_help,
            "common_mistakes": ex.common_mistakes,
        }
        manifest["plot_types"].append(entry)

        with open(os.path.join(folder, "README.md"), "w", encoding="utf-8") as fh:
            fh.write(_readme(ex, entry))

        combined_sheets.append((ex.sheet, df))
        if aux is not None and ex.aux_name:
            combined_sheets.append((f"{ex.sheet[:24]}_meta"[:31], aux))
        print(f"  {ex.plot_type}: {len(df)} rows -> {rel}")

    # Combined workbook (one sheet per plot type, plus pca metadata sheet).
    with pd.ExcelWriter(COMBINED_XLSX, engine="openpyxl") as xw:
        used = set()
        for name, df in combined_sheets:
            sheet = name[:31]
            while sheet in used:
                sheet = (sheet[:29] + "_2")[:31]
            used.add(sheet)
            df.to_excel(xw, index=False, sheet_name=sheet)

    with open(MANIFEST_PATH, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    print(f"\nWrote {len(EXAMPLES)} example datasets to {os.path.relpath(BY_PLOT_DIR, _ROOT)}")
    print(f"Combined workbook: {os.path.relpath(COMBINED_XLSX, _ROOT)}")
    print(f"Manifest: {os.path.relpath(MANIFEST_PATH, _ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
