"""Generate a reference page for every registered plot type.

The five hand-written tutorials in ``tutorial/plots/`` are screenshot-validated
walkthroughs of a real app session. They are the standard, and this does not try
to imitate them: it produces a *reference page* per plot type, built entirely
from the live registry, the bundled example manifest and the option tables, so
every column name, option, default and export format on the page is true of the
build it was generated from.

Why it exists: 40 of the 45 registered plot types had no page at all, including
all six spatial types added in v1.2.0. A reader looking up "what columns does the
oncoprint need, and what can I change" had nowhere to go.

Pages are regenerated, not edited. A hand-written tutorial for a plot type always
wins - this never overwrites one.

    python tutorial/automation/generate_plot_reference.py           # write pages
    python tutorial/automation/generate_plot_reference.py --check   # report only
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys
import warnings

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
OUT = ROOT / "tutorial" / "plots"

from make_my_figure_core import examples, ui_hints                 # noqa: E402
from make_my_figure_core.plots import registry                     # noqa: E402

GENERATED_MARK = "<!-- generated by tutorial/automation/generate_plot_reference.py -->"

# Pages written by hand, from a real app session, with screenshots. Never touched.
HAND_WRITTEN = {
    "boxplot_or_violin_with_points", "heatmap_clustered_matrix",
    "kaplan_meier_survival_curve", "scatterplot_with_regression", "volcano_plot",
}


def manifest_entries():
    path = ROOT / "examples" / "example_data_manifest.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    return {e["plot_type"]: e for e in data["plot_types"]}


def render_notes(plot_type):
    """Warnings the released build actually emits on the bundled example."""
    try:
        table, aux, spec = examples.load_example(plot_type)
        result = registry.render(spec, table.dataframe,
                                 aux={k: v.dataframe for k, v in (aux or {}).items()})
        notes = list(result.warnings)
        size = result.figure.get_size_inches()
        plt.close(result.figure)
        return notes, f"{size[0] * 25.4:.0f} x {size[1] * 25.4:.0f} mm"
    except Exception as exc:  # noqa: BLE001
        return [f"(could not render the bundled example: {type(exc).__name__}: {exc})"], "?"


def fmt_default(opt):
    if opt.default is None or opt.default == "":
        return "_(auto)_"
    if isinstance(opt.default, bool):
        return "on" if opt.default else "off"
    return f"`{opt.default}`"


def fmt_choices(opt):
    if not opt.choices:
        if opt.kind == "number" and (opt.minimum is not None or opt.maximum is not None):
            return f"{opt.minimum} to {opt.maximum}"
        return ""
    shown = [str(c) if str(c) else "(auto)" for c in opt.choices]
    text = ", ".join(f"`{c}`" for c in shown[:8])
    return text + (f", … ({len(shown)} in all)" if len(shown) > 8 else "")


def page(plot_type, entry, notes, drawn_size):
    name = registry.display_name(plot_type)
    opts = ui_hints.OPTIONS.get(plot_type, [])
    roles = ui_hints.column_fields(plot_type)
    required = entry.get("required_columns", [])
    optional = entry.get("optional_columns", [])
    files = entry.get("files", {})
    formats = entry.get("expected_export_formats", [])
    aux = entry.get("aux_tables") or {}

    L = [GENERATED_MARK, "", f"# {name}", "",
         f"Plot id `{plot_type}`. Reference page, generated from the live registry — "
         f"every column, option and default below is read from the build, not written by hand. "
         f"For a step-by-step walkthrough with screenshots see the chapter tutorials in "
         f"`tutorial/`.", ""]

    L += ["## What this plot shows", "", entry.get("description") or entry.get("use_case") or "", ""]
    if entry.get("use_case") and entry.get("use_case") != entry.get("description"):
        L += [f"**Use it when:** {entry['use_case']}", ""]

    L += ["## Example data", ""]
    if files.get("csv"):
        L += [f"Bundled: `{files['csv']}` (also "
              + ", ".join(f"`.{k}`" for k in ("tsv", "xlsx") if files.get(k)) + ").",
              "", "In the app: **Examples → " + name + "**. No download needed.", ""]
    if aux:
        L += ["This plot takes a second table as well: "
              + ", ".join(f"`{k}`" for k in aux) + ".", ""]

    L += ["## Columns", "", "| Column | Required |", "|---|---|"]
    for c in required:
        L.append(f"| `{c}` | **yes** |")
    for c in optional:
        L.append(f"| `{c}` | no |")
    if not required and not optional:
        L.append("| _(none declared)_ | |")
    L += ["", f"Column roles the app asks you to fill: "
          + ", ".join(f"**{r}**" for r in roles) + ".", "",
          "Your column names do not have to match. If the app cannot guess a role it leaves it "
          "blank and says so in the Messages tab; set it yourself from the dropdown. See "
          "`tutorial/01_Data_and_Column_Mapping/your_table_does_not_need_perfect_column_names.md`.",
          ""]

    L += [f"## Options ({len(opts)})", ""]
    if opts:
        L += ["| Option | Key | Type | Default | Values |", "|---|---|---|---|---|"]
        for o in opts:
            L.append(f"| {o.label} | `{o.key}` | {o.kind} | {fmt_default(o)} | {fmt_choices(o)} |")
    else:
        L.append("_This plot type declares no options of its own; the shared style, "
                 "figure-size and export settings still apply._")
    L += [""]

    L += ["## Publication settings", "",
          "- **Figure width** — pick `single`, `onehalf` or `double`, or type a measurement such "
          "as `89mm`. Since v1.2.0 the width you ask for is the width you get on every plot type; "
          "if the content cannot fit, the plot area gives up the room and the render says so "
          "rather than handing back a different size.",
          "- **Style profile** — " + ", ".join(f"`{p}`" for p in
                                               (entry.get("recommended_style_profiles") or ["publication"])) + ".",
          f"- The bundled example draws at **{drawn_size}** with the shipped defaults.", ""]

    L += ["## Save, reopen and share", "",
          "- **Save PlotSpec** writes the figure's recipe as JSON; *Open PlotSpec* rebuilds it "
          "against data with the same columns.",
          "- **Save Reproducible Figure Package (`.mmfpackage`)** writes the recipe *and* a frozen "
          "lossless copy of the exact table used, so the figure reopens on another computer with "
          "no access to the original file. Verified for this plot type in the v1.2.0 release audit.",
          "- **Export** — " + ", ".join(f"`{f}`" for f in (formats or ["png", "svg", "pdf"])) + ".", ""]

    L += ["## What the released build says about the bundled example", ""]
    if notes:
        L += ["Rendering the example on v1.2.0 produces these messages:", ""]
        L += [f"- {n}" for n in notes]
        L += ["", "They are the renderer telling you what it did or what it could not do — worth "
              "reading rather than dismissing.", ""]
    else:
        L += ["Rendering the example on v1.2.0 produces no warnings.", ""]

    L += ["## Common pitfalls", "",
          "- A required column left unmapped: the figure does not draw and the Messages tab names "
          "the missing role.",
          "- Expecting the app to compute statistics it does not: MakeMyFigure plots what the "
          "table says and reports which test produced a value; it does not silently invent one.",
          "- Asking for a narrow column with a large key: the width is honoured and the plot area "
          "shrinks. Widen the figure, shorten the labels, or move the key inside the axes.", ""]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report, write nothing")
    args = ap.parse_args()
    warnings.filterwarnings("ignore")

    entries = manifest_entries()
    plot_types = sorted(registry.available_plot_types())
    written, skipped, missing_entry = [], [], []

    for pt in plot_types:
        if pt in HAND_WRITTEN:
            skipped.append(pt)
            continue
        entry = entries.get(pt)
        if entry is None:
            missing_entry.append(pt)
            continue
        notes, size = render_notes(pt)
        text = page(pt, entry, notes, size)
        target = OUT / f"{pt}.md"
        if target.exists() and GENERATED_MARK not in target.read_text(encoding="utf-8"):
            skipped.append(pt)          # hand-written page we did not know about
            continue
        if not args.check:
            target.write_text(text, encoding="utf-8")
        written.append(pt)

    print(f"registered plot types: {len(plot_types)}")
    print(f"  reference pages {'to write' if args.check else 'written'}: {len(written)}")
    print(f"  hand-written, left alone: {len(skipped)}  {sorted(skipped)}")
    if missing_entry:
        print(f"  NO manifest entry: {missing_entry}")
    return 1 if missing_entry else 0


if __name__ == "__main__":
    raise SystemExit(main())
